# -*- coding: utf-8 -*-
"""data_preparation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gB8MqLcA5QztJC5Zb1EYRMBcm7GH1fo5
"""

# -*- coding: utf-8 -*-
"""
Dataset Preparation Module

This module prepares segmented audio datasets for the age verification experiments.

Supported datasets
------------------
1. Common Voice
   - Metadata provides age and gender labels.
   - Age labels are converted into a binary setting: child vs adult.

2. MyST
   - No speaker metadata is used.
   - All samples are treated as child speech.

Processing overview
-------------------
1. Load dataset metadata or scan audio files.
2. Preserve the original train/valid/test split.
3. Build full paths to audio recordings.
4. Apply the audio preprocessing pipeline.
5. Segment each recording into fixed-length windows.
6. Save the generated segments to disk.
7. Store metadata for each saved segment.
"""

import os
import kagglehub
import pandas as pd
from tqdm import tqdm

from preprocessing import preprocess_by_dataset, save_segment_as_wav


# Kaggle identifier for Common Voice
COMMON_VOICE_NAME = "mozillaorg/common-voice"


# =========================================================
# Utility Functions
# =========================================================
def show_metadata_distribution(df: pd.DataFrame, title: str) -> None:
    """
    Display basic statistics for a metadata dataframe.

    Parameters
    ----------
    df : pd.DataFrame
        Input metadata dataframe.
    title : str
        Title describing the current stage of processing.
    """
    print(f"\n=== {title} ===")

    if "age" in df.columns:
        print("\nAge distribution:")
        print(df["age"].value_counts(dropna=False))

    if "gender" in df.columns:
        print("\nGender distribution:")
        print(df["gender"].value_counts(dropna=False))

    if "split" in df.columns:
        print("\nSplit distribution:")
        print(df["split"].value_counts(dropna=False))

    print("\nTotal rows:", len(df))


# =========================================================
# Common Voice: Load metadata
# =========================================================
def load_common_voice_metadata() -> tuple[pd.DataFrame, str]:
    """
    Download Common Voice and load metadata for all official splits.

    Returns
    -------
    df : pd.DataFrame
        Combined metadata dataframe for train, valid, and test splits.
    dataset_path : str
        Root path of the downloaded Common Voice dataset.
    """
    dataset_path = kagglehub.dataset_download(COMMON_VOICE_NAME)
    print("Common Voice dataset path:", dataset_path)

    # Each split has its own metadata file
    split_files = {
        "train": "cv-valid-train.csv",
        "valid": "cv-valid-dev.csv",
        "test": "cv-valid-test.csv",
    }

    frames = []

    for split_name, file_name in split_files.items():
        csv_path = os.path.join(dataset_path, file_name)

        if not os.path.exists(csv_path):
            print(f"Warning: metadata file not found: {csv_path}")
            continue

        df_split = pd.read_csv(csv_path)

        # Keep track of the original split
        df_split["split"] = split_name

        frames.append(df_split)

    if not frames:
        raise ValueError("No Common Voice metadata files were found.")

    df = pd.concat(frames, ignore_index=True)

    return df, dataset_path


# =========================================================
# Common Voice: Clean metadata
# =========================================================
def clean_common_voice_metadata(df: pd.DataFrame) -> pd.DataFrame:
    """
    Clean Common Voice metadata and convert age labels to binary classes.

    Processing steps
    ----------------
    1. Remove rows with missing age or gender.
    2. Remove rows where gender is labeled as 'other'.
    3. Convert age labels into:
       - child  -> teens
       - adult  -> all remaining age categories
    """
    df = df.dropna(subset=["age", "gender"]).copy()
    df = df[df["gender"] != "other"]

    df["age"] = df["age"].apply(
        lambda x: "child" if x == "teens" else "adult"
    )

    return df


# =========================================================
# Common Voice: Build audio paths
# =========================================================
def add_common_voice_audio_paths(
    df: pd.DataFrame,
    dataset_path: str
) -> pd.DataFrame:
    """
    Build full audio paths for Common Voice recordings based on split.

    Parameters
    ----------
    df : pd.DataFrame
        Common Voice metadata dataframe.
    dataset_path : str
        Root path of the Common Voice dataset.

    Returns
    -------
    pd.DataFrame
        Metadata dataframe with an additional 'audio_path' column.
    """
    split_to_folder = {
        "train": "cv-valid-train",
        "valid": "cv-valid-dev",
        "test": "cv-valid-test",
    }

    df = df.copy()

    df["audio_path"] = df.apply(
        lambda row: os.path.join(
            dataset_path,
            split_to_folder[row["split"]],
            row["filename"],
        ),
        axis=1,
    )

    return df


# =========================================================
# MyST: Scan audio files
# =========================================================
def load_myst_audio_paths(myst_root_dir: str) -> pd.DataFrame:
    """
    Scan the MyST dataset directory and collect audio file paths.

    Assumptions
    -----------
    1. The dataset is organized into train / development / test folders.
    2. All samples are treated as child speech.
    3. Gender information is not used.
    4. Audio files are stored as .flac files.

    Parameters
    ----------
    myst_root_dir : str
        Root directory of the MyST dataset.

    Returns
    -------
    pd.DataFrame
        Dataframe containing audio_path, age, gender, and split.
    """
    records = []

    split_map = {
        "train": "train",
        "valid": "development",
        "test": "test"
    }

    all_files = []

    for split_name, folder_name in split_map.items():
        split_dir = os.path.join(myst_root_dir, folder_name)

        if not os.path.exists(split_dir):
            print(f"Warning: split folder not found: {split_dir}")
            continue

        for root, _, files in os.walk(split_dir):
            for file_name in files:
                if file_name.lower().endswith(".flac"):
                    all_files.append({
                        "audio_path": os.path.join(root, file_name),
                        "age": "child",
                        "gender": "NA",
                        "split": split_name
                    })

    for record in tqdm(all_files, desc="Scanning MyST audio"):
        records.append(record)

    df = pd.DataFrame(records)

    print("Total MyST audio files:", len(df))

    if len(df) > 0:
        print("\nMyST split distribution:")
        print(df["split"].value_counts())

    return df


# =========================================================
# Shared Processing: Segment generation and saving
# =========================================================
def process_segments(
    df: pd.DataFrame,
    processed_dir: str,
    dataset_name: str,
    spoof_label: int,
    remove_internal_silence: bool,
    top_db: int,
    seg_sec: float,
    hop_sec: float,
) -> pd.DataFrame:
    """
    Apply preprocessing, segment each recording, and save the outputs.

    For each recording:
    1. Run dataset-specific preprocessing.
    2. Generate fixed-length segments.
    3. Save each segment as a WAV file.
    4. Store metadata for each saved segment.

    Parameters
    ----------
    df : pd.DataFrame
        Input metadata dataframe.
    processed_dir : str
        Directory where processed segments will be saved.
    dataset_name : str
        Dataset identifier ('cv' or 'myst').
    remove_internal_silence : bool
        Whether to remove internal non-speech regions.
    top_db : int
        Silence threshold used for edge trimming.
    seg_sec : float
        Segment length in seconds.
    hop_sec : float
        Hop length in seconds.

    Returns
    -------
    pd.DataFrame
        Segment-level metadata dataframe.
    """
    os.makedirs(processed_dir, exist_ok=True)

    segment_records = []

    for idx, row in tqdm(df.iterrows(), total=len(df), desc=f"Processing {dataset_name}"):
        audio_path = row["audio_path"]

        try:
            # Apply the preprocessing pipeline for the selected dataset
            segments = preprocess_by_dataset(
                audio_path=audio_path,
                dataset_name=dataset_name,
                remove_internal_silence=remove_internal_silence,
                top_db=top_db,
                seg_sec=seg_sec,
                hop_sec=hop_sec,
            )

            # Skip files that produced no usable segments
            if len(segments) == 0:
                continue

            for seg_idx in range(len(segments)):
                # Create a unique filename for each generated segment
                file_name = f"{dataset_name}_{row['split']}_id{idx:06d}_seg{seg_idx:02d}.wav"
                segment_path = os.path.join(processed_dir, file_name)

                # Save the current segment
                save_segment_as_wav(
                    segment=segments[seg_idx],
                    output_path=segment_path
                )

                # Store metadata describing this segment
                segment_records.append({
                  "original_audio_path": audio_path,
                  "segment_path": segment_path,
                  "dataset": dataset_name,
                  "split": row["split"],
                  "age": row["age"],
                  "gender": row["gender"],
                  "spoof_label": spoof_label,
                  "sample_id": idx,
                  "segment_id": seg_idx,
              })

        except Exception as e:
            print(f"Error processing {audio_path}: {e}")

    segments_df = pd.DataFrame(segment_records)

    print(f"\nTotal saved {dataset_name} segments:", len(segments_df))

    return segments_df


# =========================================================
# Public API: Prepare Common Voice
# =========================================================
def prepare_common_voice_dataset(
    processed_dir: str,
    remove_internal_silence: bool = False,
    top_db: int = 30,
    seg_sec: float = 3.0,
    hop_sec: float = 1.5,
) -> pd.DataFrame:
    """
    Prepare segmented Common Voice data.

    Parameters
    ----------
    processed_dir : str
        Directory where processed segments will be saved.
    remove_internal_silence : bool, default=False
        Whether to remove internal non-speech regions.
    top_db : int, default=30
        Silence threshold used for edge trimming.
    seg_sec : float, default=3.0
        Segment length in seconds.
    hop_sec : float, default=1.5
        Hop length in seconds.

    Returns
    -------
    pd.DataFrame
        Segment-level metadata dataframe for Common Voice.
    """
    # Load original metadata and split labels
    df, dataset_path = load_common_voice_metadata()
    show_metadata_distribution(df, "COMMON VOICE - BEFORE CLEANING")

    # Clean metadata and convert age labels
    df = clean_common_voice_metadata(df)
    show_metadata_distribution(df, "COMMON VOICE - AFTER CLEANING")

    # Build full paths to the audio files
    df = add_common_voice_audio_paths(df, dataset_path)

    # Process recordings and save segments
    return process_segments(
        df=df,
        processed_dir=processed_dir,
        dataset_name="cv",
        spoof_label=0,
        remove_internal_silence=remove_internal_silence,
        top_db=top_db,
        seg_sec=seg_sec,
        hop_sec=hop_sec,
    )


# =========================================================
# Public API: Prepare MyST
# =========================================================
def prepare_myst_dataset(
    myst_root_dir: str,
    processed_dir: str,
    remove_internal_silence: bool = False,
    top_db: int = 30,
    seg_sec: float = 3.0,
    hop_sec: float = 1.5,
) -> pd.DataFrame:
    """
    Prepare segmented MyST data.

    Parameters
    ----------
    myst_root_dir : str
        Root directory of the MyST dataset.
    processed_dir : str
        Directory where processed segments will be saved.
    remove_internal_silence : bool, default=False
        Whether to remove internal non-speech regions.
    top_db : int, default=30
        Silence threshold used for edge trimming.
    seg_sec : float, default=3.0
        Segment length in seconds.
    hop_sec : float, default=1.5
        Hop length in seconds.

    Returns
    -------
    pd.DataFrame
        Segment-level metadata dataframe for MyST.
    """
    # Scan MyST audio files while preserving the original split
    df = load_myst_audio_paths(myst_root_dir)

    # Process recordings and save segments
    return process_segments(
        df=df,
        processed_dir=processed_dir,
        dataset_name="myst",
        spoof_label=0,
        remove_internal_silence=remove_internal_silence,
        top_db=top_db,
        seg_sec=seg_sec,
        hop_sec=hop_sec,
    )


# =========================================================
# Public API: Generic Dispatcher
# =========================================================
def prepare_dataset(
    dataset_name: str,
    processed_dir: str,
    remove_internal_silence: bool = False,
    top_db: int = 30,
    seg_sec: float = 3.0,
    hop_sec: float = 1.5,
    myst_root_dir: str | None = None,
) -> pd.DataFrame:
    """
    Prepare one dataset by name.

    Parameters
    ----------
    dataset_name : str
        Dataset identifier. Supported values are 'cv' and 'myst'.
    processed_dir : str
        Directory where processed segments will be saved.
    remove_internal_silence : bool, default=False
        Whether to remove internal non-speech regions.
    top_db : int, default=30
        Silence threshold used for edge trimming.
    seg_sec : float, default=3.0
        Segment length in seconds.
    hop_sec : float, default=1.5
        Hop length in seconds.
    myst_root_dir : str or None, default=None
        Root directory of MyST. Required only when dataset_name='myst'.

    Returns
    -------
    pd.DataFrame
        Segment-level metadata dataframe.
    """
    dataset_name = dataset_name.lower()

    if dataset_name == "cv":
        return prepare_common_voice_dataset(
            processed_dir=processed_dir,
            remove_internal_silence=remove_internal_silence,
            top_db=top_db,
            seg_sec=seg_sec,
            hop_sec=hop_sec,
        )

    if dataset_name == "myst":
        if myst_root_dir is None:
            raise ValueError("myst_root_dir must be provided for MyST.")
        return prepare_myst_dataset(
            myst_root_dir=myst_root_dir,
            processed_dir=processed_dir,
            remove_internal_silence=remove_internal_silence,
            top_db=top_db,
            seg_sec=seg_sec,
            hop_sec=hop_sec,
        )

    raise ValueError(f"Unknown dataset_name: {dataset_name}")