# -*- coding: utf-8 -*-
"""file_manifest_builder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/136GId4VnNCH1neAKz_J2MbBeeRj53IYB
"""

# -*- coding: utf-8 -*-
"""
Data Preparation Module

This module handles loading speaker splits and file-level metadata,
and builds the unified file manifest used by the preprocessing pipeline.

Overview
--------
The age verification pipeline requires structured file-level information
before any audio preprocessing can begin. This module performs the following:

1. Speaker splits
   One or more CSV files define which speakers belong to train, val, and test splits.
   Each file corresponds to a specific data pool (e.g., adult_real_candidates).
   These splits are created at the speaker level to ensure that no speaker appears
   in more than one split, preventing data leakage.

2. File-level metadata
   Each dataset source provides metadata linking speakers to audio files.
   The formats differ, so they are normalized into a shared schema.

3. File manifest construction
   The final output is a single CSV file (file_manifest.csv), where each row
   corresponds to one audio file and contains all required attributes
   for downstream processing.

Output
------
The generated file_manifest contains the following columns:

- dataset           : dataset source (common_voice, myst, voxceleb)
- speaker_id        : unique speaker identifier
- file_id           : unique file identifier
- path              : absolute path to the audio file
- raw_duration_sec  : duration of the audio file in seconds
- split             : train, val, or test
- pool              : data grouping label (e.g., adult_real_candidates)
"""

import os
import pandas as pd


# =========================================================
# Metadata loading
# =========================================================

def load_cv_metadata(cv_meta_path):
    """
    Load and normalize Common Voice metadata.

    Uses clips_path as the file path column and assigns
    the dataset source label.
    """
    df = pd.read_csv(cv_meta_path, low_memory=False)

    df = df.rename(columns={"client_id": "speaker_id"})
    df["path"] = df["clips_path"]
    df["dataset"] = "common_voice"

    return df[["speaker_id", "dataset", "path", "duration_sec"]]


def load_myst_metadata(myst_meta_path):
    """
    Load and normalize MyST metadata.

    Adds dataset source label and returns standardized columns.
    """
    df = pd.read_csv(myst_meta_path, dtype={"speaker_id": str})
    df["speaker_id"] = df["speaker_id"].astype(str).str.strip().str.zfill(6)
    df = df.rename(columns={"full_path": "path"})
    df["dataset"] = "myst"
    return df[["speaker_id", "dataset", "path", "duration_sec"]]


def load_voxceleb_metadata(vox_meta_path):
    """
    Load and normalize VoxCeleb metadata.

    Adds dataset source label and returns standardized columns.
    """
    df = pd.read_csv(vox_meta_path)
    df = df.rename(columns={"full_path": "path"})
    df["dataset"] = "voxceleb"
    return df[["speaker_id", "dataset", "path", "duration_sec"]]


def load_metadata(cv_meta_path, myst_meta_path, vox_meta_path):
    """
    Load and combine metadata from all dataset sources.

    Each dataset is normalized independently, then concatenated
    into a single unified DataFrame.
    """
    cv_meta   = load_cv_metadata(cv_meta_path)
    myst_meta = load_myst_metadata(myst_meta_path)
    vox_meta  = load_voxceleb_metadata(vox_meta_path)
    return pd.concat([cv_meta, myst_meta, vox_meta], ignore_index=True)


# =========================================================
# File manifest builder
# =========================================================

def build_file_manifest(role_inventory_paths, cv_meta_path, myst_meta_path, vox_meta_path):
    """
    Build the unified file manifest.

    Processing steps
    ----------------
    1. Load file-level metadata from all dataset sources.
    2. Iterate over all role inventory files.
    3. Filter metadata to keep only files whose speakers are listed in the current inventory.
    4. Merge speaker information with file-level metadata.
    5. Construct the pool label based on the role name.
    6. Concatenate all pool-specific manifests.
    7. Generate file_id and rename columns to match manifest format.
    8. Save the final file_manifest.csv.

    Returns
    -------
    pd.DataFrame
        Final file manifest ready for preprocessing.
    """

    # Step 1: Load metadata once
    all_meta = load_metadata(cv_meta_path, myst_meta_path, vox_meta_path)

    manifest_parts = []

    # Step 2: Process each inventory file
    for role_inventory_path in role_inventory_paths:
        speakers = pd.read_csv(role_inventory_path, dtype={"speaker_id": str})
        speakers["speaker_id"] = speakers["speaker_id"].astype(str).str.strip()

        if "dataset_source" in speakers.columns:
            myst_mask = speakers["dataset_source"] == "myst"
            speakers.loc[myst_mask, "speaker_id"] = speakers.loc[myst_mask, "speaker_id"].str.zfill(6)

        target_ids = set(speakers["speaker_id"])

        # Step 3: Filter by target speakers
        filtered_meta = all_meta[all_meta["speaker_id"].isin(target_ids)].copy()

        # Step 4: Merge speaker info
        file_list = filtered_meta.merge(
            speakers[["speaker_id", "split", "dataset_source"]].rename(columns={"dataset_source": "dataset"}),
            on=["speaker_id", "dataset"],
            how="inner",
        )

        assert len(file_list) == len(filtered_meta), f"Merge mismatch in {role_inventory_path}"

        # Step 5: Build pool
        role_name = os.path.basename(role_inventory_path).replace("_split.csv", "")
        file_list["pool"] = role_name

        manifest_parts.append(file_list)

    # Step 6: Combine all pools
    file_manifest = pd.concat(manifest_parts, ignore_index=True)

    # Step 7: Rename columns
    file_manifest = file_manifest.rename(columns={
        "duration_sec": "raw_duration_sec"
    }).copy()

    # Generate file_id
    file_manifest["file_id"] = [
        f"{ds}_{spk}_{i:06d}"
        for i, (ds, spk) in enumerate(
            zip(file_manifest["dataset"], file_manifest["speaker_id"]),
            start=1
        )
    ]

    # Select final columns
    file_manifest = file_manifest[
        ["dataset", "speaker_id", "file_id", "path", "raw_duration_sec", "split", "pool"]
    ]

    # Step 8: Save
    out_path = "/content/drive/MyDrive/age verification/processed/file_manifest.csv"
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    file_manifest.to_csv(out_path, index=False)

    # Summary
    print(f"Total speakers: {file_manifest['speaker_id'].nunique()}")
    print(f"Total files:    {len(file_manifest)}")
    print("file_manifest.csv saved!")

    return file_manifest