# -*- coding: utf-8 -*-
"""Gaussian Noise .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QdOvWwa4EfOh1DuWgEFpAZeNLbxLqeVL
"""

"""
Gaussian Noise Augmentation Pipeline
-------------------------------------

This module implements Gaussian noise augmentation for audio segments across
training, validation, and test splits.

Objectives
----------
1. Training Augmentation (On-the-Fly):
   Apply random Gaussian noise during training without saving files:
   - Noise level is sampled per batch using predefined probabilities.
   - No disk I/O overhead during training.

2. Validation Noise Generation (Fixed):
   Generate and save fixed noisy versions of validation segments:
   - Each segment receives one noise level sampled from NOISE_PROBS.
   - Sampling is seeded for reproducibility across runs.

3. Test Noise Generation (Fixed):
   Generate and save fixed noisy versions of test segments under a single
   noise condition:
   - All segments receive the same condition (no random sampling).
   - Designed for controlled evaluation across noise levels.

Noise Levels
------------
- clean : No noise added (SNR = None).
- low   : SNR = 20 dB
- med   : SNR = 10 dB
- hard  : SNR = 5 dB

Sampling Probabilities (Validation / Training)
----------------------------------------------
- clean : 50%
- low   : 25%
- med   : 20%
- hard  : 5%

Test Conditions
---------------
- clean : No noise.
- 20dB  : SNR = 20 dB
- 10dB  : SNR = 10 dB
- 5dB   : SNR = 5 dB

Outputs
-------
Validation:
- Noisy .wav files saved to output_audio_dir.
- Updated metadata CSV with columns: noise_type, noise_level, snr_db, noisy_path.

Test:
- Noisy .wav files saved to output_audio_dir.
- Updated metadata CSV with columns: noise_type, noise_level, snr_db, noisy_path.

Notes
-----
- Training augmentation is on-the-fly; no files are written to disk.
- Validation uses a fixed seed to ensure the same noise assignments across runs.
- Test evaluation runs one condition at a time for controlled benchmarking.
- All waveforms are clamped to [-1.0, 1.0] after noise addition.
"""

import os
import numpy as np
import pandas as pd
import torch
import torchaudio
import soundfile as sf


NOISE_LEVELS = {
    "clean": None,
    "low": 20,
    "med": 10,
    "hard": 5
}

NOISE_PROBS = {
    "clean": 0.50,
    "low": 0.25,
    "med": 0.20,
    "hard": 0.05
}

TEST_CONDITION_MAP = {
    "clean": None,
    "20dB": 20,
    "10dB": 10,
    "5dB": 5
}


def add_gaussian_noise(waveform, snr_db):
    """
    Add Gaussian noise to a waveform at a specified SNR level.

    Args:
        waveform (Tensor): Input audio waveform, shape (samples,).
        snr_db (float or None): Target SNR in dB. If None, returns waveform unchanged.

    Returns:
        Tensor: Noisy waveform clamped to [-1.0, 1.0], same shape as input.
    """
    if snr_db is None:
        return waveform

    signal_power = waveform.pow(2).mean()
    snr_linear = 10 ** (snr_db / 10)
    noise_power = signal_power / snr_linear

    noise = torch.randn_like(waveform) * torch.sqrt(noise_power)
    noisy_waveform = waveform + noise

    return torch.clamp(noisy_waveform, -1.0, 1.0)


def train_gaussian_noise_transform(waveform, item=None):
    """
    Apply random Gaussian noise augmentation for training (on-the-fly).
    Noise level is sampled from NOISE_PROBS each call — no files saved.

    Args:
        waveform (Tensor): Input audio waveform, shape (samples,).
        item: Unused. Reserved for dataset item compatibility.

    Returns:
        tuple:
            - waveform (Tensor): Augmented waveform.
            - noise_type (str): "gaussian" or "none" if clean.
            - snr_db (int or str): SNR value in dB, or "clean" if no noise added.
    """
    noise_level = np.random.choice(
        list(NOISE_PROBS.keys()),
        p=list(NOISE_PROBS.values())
    )

    snr_db = NOISE_LEVELS[noise_level]
    waveform = add_gaussian_noise(waveform, snr_db)

    if noise_level == "clean":
        return waveform, "none", "clean"

    return waveform, "gaussian", snr_db


def generate_fixed_validation_noise(
    metadata_path,
    output_audio_dir,
    output_metadata_path,
    path_column="seg_path",
    seed=42
):
    """
    Generate and save fixed noisy versions of validation segments.
    Each segment gets one noise level sampled from NOISE_PROBS using a fixed seed.

    Args:
        metadata_path (str): Path to validation metadata CSV.
        output_audio_dir (str): Directory where noisy .wav files will be saved.
        output_metadata_path (str): Path to save the updated metadata CSV.
        path_column (str): Column in metadata holding audio file paths. Default: "seg_path".
        seed (int): Random seed for reproducible noise assignment. Default: 42.

    Returns:
        DataFrame: Updated metadata with added columns:
                   noise_type, snr_db, noisy_path.
    """
    df = pd.read_csv(metadata_path)
    os.makedirs(output_audio_dir, exist_ok=True)
    os.makedirs(os.path.dirname(output_metadata_path), exist_ok=True)

    rng = np.random.default_rng(seed)
    new_rows = []

    for _, row in df.iterrows():
        audio_path = row[path_column]

        waveform, sr = torchaudio.load(audio_path)
        waveform = waveform.squeeze(0)

        noise_level = rng.choice(
            list(NOISE_PROBS.keys()),
            p=list(NOISE_PROBS.values())
        )

        snr_db = NOISE_LEVELS[noise_level]
        noisy_waveform = add_gaussian_noise(waveform, snr_db)

        original_name = os.path.splitext(os.path.basename(audio_path))[0]
        output_path = os.path.join(output_audio_dir, f"{original_name}_{noise_level}.wav")

        sf.write(output_path, noisy_waveform.cpu().numpy(), sr)

        new_row = row.to_dict()
        new_row["noise_type"] = "none" if noise_level == "clean" else "gaussian"
        new_row["snr_db"] = "clean" if snr_db is None else snr_db
        new_row["seg_path"] = output_path

        new_rows.append(new_row)

    new_df = pd.DataFrame(new_rows)
    new_df.to_csv(output_metadata_path, index=False)

    print("Validation noise generation completed.")
    print(f"Audio saved to: {output_audio_dir}")
    print(f"Metadata saved to: {output_metadata_path}")

    return new_df


def generate_fixed_test_noise(
    metadata_path,
    output_audio_dir,
    output_metadata_path,
    noise_condition,
    path_column="seg_path"
):
    """
    Generate and save fixed noisy versions of test segments under one noise condition.
    Unlike validation, all segments receive the same condition — no random sampling.

    Args:
        metadata_path (str): Path to test metadata CSV.
        output_audio_dir (str): Directory where noisy .wav files will be saved.
        output_metadata_path (str): Path to save the updated metadata CSV.
        noise_condition (str): One of ["clean", "20dB", "10dB", "5dB"].
        path_column (str): Column in metadata holding audio file paths. Default: "seg_path".

    Returns:
        DataFrame: Updated metadata with added columns:
                   noise_type, snr_db, noisy_path.

    Raises:
        ValueError: If noise_condition is not one of the accepted values.
    """
    if noise_condition not in TEST_CONDITION_MAP:
        raise ValueError("noise_condition must be one of: clean, 20dB, 10dB, 5dB")

    df = pd.read_csv(metadata_path)
    os.makedirs(output_audio_dir, exist_ok=True)
    os.makedirs(os.path.dirname(output_metadata_path), exist_ok=True)

    snr_db = TEST_CONDITION_MAP[noise_condition]
    new_rows = []

    for _, row in df.iterrows():
        audio_path = row[path_column]

        waveform, sr = torchaudio.load(audio_path)
        waveform = waveform.squeeze(0)

        noisy_waveform = add_gaussian_noise(waveform, snr_db)

        original_name = os.path.splitext(os.path.basename(audio_path))[0]
        output_path = os.path.join(output_audio_dir, f"{original_name}_{noise_condition}.wav")

        sf.write(output_path, noisy_waveform.cpu().numpy(), sr)

        new_row = row.to_dict()
        new_row["noise_type"] = "none" if noise_condition == "clean" else "gaussian"
        new_row["snr_db"] = "clean" if snr_db is None else snr_db
        new_row["seg_path"] = output_path

        new_rows.append(new_row)

    new_df = pd.DataFrame(new_rows)
    new_df.to_csv(output_metadata_path, index=False)

    print(f"Test noise generation completed: {noise_condition}")
    print(f"Audio saved to: {output_audio_dir}")
    print(f"Metadata saved to: {output_metadata_path}")

    return new_df
