# -*- coding: utf-8 -*-
"""local_data_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ym7JGu_p_FM7Up8r_eF_uJuK5xc_sELJ
"""

"""
Local Runtime Data Utilities

This module provides utilities for preparing large audio datasets for
efficient training and evaluation in Google Colab or similar environments.

Overview
--------
The workflow is designed to reduce Google Drive I/O bottlenecks by:
1. Copying only required audio files locally using rsync
2. Creating compressed tar archives for reuse
3. Extracting archives into local runtime storage
4. Updating CSV manifests so audio paths point to local files

Main Features
-------------
- Build relative file lists from CSV manifests
- Copy only required files using rsync
- Create reusable tar archives
- Extract archives locally
- Automatically update manifest paths
- Prepare train/validation/test manifests for local runtime

Typical Usage
-------------
1. Prepare local audio files from manifests:
    prepare_local_files(...)

2. Create reusable tar archive:
    create_tar(...)

3. Load archive in future sessions:
    load_archive_to_local(...)

Notes
-----
- Designed for speech/audio experiments
- Optimized for Google Colab workflows
- Assumes manifests contain absolute Drive paths
"""

import os
import shutil
import subprocess
import pandas as pd


# =========================================================
# Build File List
# =========================================================

def build_file_list(csv_paths, output_txt_path,
                    base_dir, path_col="seg_path"):
    """
    Build a text file containing unique relative audio paths.

    This file can later be used with rsync to selectively copy
    only required audio files from Drive to local runtime.

    Parameters
    ----------
    csv_paths : list
        List of CSV manifest paths.

    output_txt_path : str
        Path where the file list will be saved.

    base_dir : str
        Root directory that should be removed from absolute paths
        to create relative paths for rsync.

    path_col : str
        Column containing audio paths.

    Returns
    -------
    np.ndarray
        Array of unique audio paths.
    """

    # Load all audio paths from manifests
    paths = pd.concat([
        pd.read_csv(p)[path_col]
        for p in csv_paths
    ]).dropna().unique()

    # Convert absolute paths → relative paths
    relative_paths = [
        p.replace(base_dir + "/", "")
        for p in paths
    ]

    # Save file list
    with open(output_txt_path, "w") as f:
        f.write("\n".join(relative_paths))

    print(f"Files: {len(paths)}")
    print(f"Saved file list → {output_txt_path}")

    return paths


# =========================================================
# Rsync Required Files
# =========================================================

def rsync_files(file_list_path,
                source_base_dir,
                local_dir="/content/audio_data"):
    """
    Copy only required audio files to local runtime.

    Uses rsync with --files-from for efficient selective copying.

    Parameters
    ----------
    file_list_path : str
        Text file containing relative audio paths.

    source_base_dir : str
        Source root directory in Drive.

    local_dir : str
        Local runtime directory where files will be copied.
    """

    # Create local runtime directory if missing
    os.makedirs(local_dir, exist_ok=True)

    # Rsync only required files
    subprocess.run([
        "rsync",
        "-ah",
        "--ignore-existing",
        "--info=progress2",
        f"--files-from={file_list_path}",
        source_base_dir + "/",
        local_dir + "/"
    ], check=True)

    print(f"Copied required files → {local_dir}")


# =========================================================
# Update Manifest Paths
# =========================================================

def update_manifest_paths(
    csv_path,
    out_csv_path,
    drive_base_dir,
    local_base_dir="/content/audio_data",
    audio_col="seg_path"
):
    """
    Replace Drive audio paths with local runtime paths.

    Parameters
    ----------
    csv_path : str
        Original CSV manifest path.

    out_csv_path : str
        Output path for updated local manifest.

    drive_base_dir : str
        Base Drive directory to replace.

    local_base_dir : str
        Local runtime directory.

    audio_col : str
        Column containing audio paths.

    Returns
    -------
    str
        Path to updated local CSV manifest.
    """

    # Load manifest
    df = pd.read_csv(csv_path)

    print(f"Loaded: {csv_path}")
    print(f"Rows: {len(df)}")

    # Replace Drive paths → local runtime paths
    df[audio_col] = df[audio_col].str.replace(
        drive_base_dir,
        local_base_dir,
        regex=False
    )

    print("Updated paths to local runtime.")

    # Save updated manifest
    df.to_csv(out_csv_path, index=False)

    print(f"Saved local manifest → {out_csv_path}")

    return out_csv_path


# =========================================================
# Full Local Preparation Pipeline
# =========================================================

def prepare_local_files(
    csv_paths,
    output_txt_path,
    base_dir,
    local_dir="/content/audio_data",
    local_manifest_dir="/content/local_manifests",
    path_col="seg_path"
):
    """
    Full local preparation pipeline.

    Workflow
    --------
    1. Build file list from manifests
    2. Copy required files locally using rsync
    3. Create updated local manifests

    Parameters
    ----------
    csv_paths : list
        List of CSV manifest paths.

    output_txt_path : str
        File list output path.

    base_dir : str
        Original Drive data root.

    local_dir : str
        Local runtime audio directory.

    local_manifest_dir : str
        Directory where updated manifests will be saved.

    path_col : str
        Column containing audio paths.

    Returns
    -------
    list
        List of updated local CSV manifest paths.
    """

    # Create local manifest directory
    os.makedirs(local_manifest_dir, exist_ok=True)

    # -----------------------------------------------------
    # Build relative file list
    # -----------------------------------------------------

    build_file_list(
        csv_paths=csv_paths,
        output_txt_path=output_txt_path,
        base_dir=base_dir,
        path_col=path_col
    )

    # -----------------------------------------------------
    # Copy required audio files locally
    # -----------------------------------------------------

    rsync_files(
        file_list_path=output_txt_path,
        source_base_dir=base_dir,
        local_dir=local_dir
    )

    # -----------------------------------------------------
    # Create updated local manifests
    # -----------------------------------------------------

    local_csv_paths = []

    for csv_path in csv_paths:

        # Extract filename
        filename = os.path.basename(csv_path)

        # Create output CSV name
        out_csv_path = os.path.join(
            local_manifest_dir,
            filename.replace(".csv", "_local.csv")
        )

        # Update manifest paths
        local_csv = update_manifest_paths(
            csv_path=csv_path,
            out_csv_path=out_csv_path,
            drive_base_dir=base_dir,
            local_base_dir=local_dir,
            audio_col=path_col
        )

        local_csv_paths.append(local_csv)

    print("\nLocal manifests ready.")

    return local_csv_paths


# =========================================================
# Create Tar Archive
# =========================================================

def create_tar(local_dir, folders, tar_path):
    """
    Create compressed tar archive from selected folders.

    Parameters
    ----------
    local_dir : str
        Root directory containing folders.

    folders : list
        Folder names to include in archive.

    tar_path : str
        Output tar file path.

    Returns
    -------
    str
        Created tar archive path.
    """

    cmd = ["tar", "-cf", tar_path, "-C", local_dir] + folders

    subprocess.run(cmd, check=True)

    print(f"Created archive → {tar_path}")

    return tar_path


# =========================================================
# Copy File
# =========================================================

def copy_file(src, dst):
    """
    Copy file from source to destination.

    Parameters
    ----------
    src : str
        Source file path.

    dst : str
        Destination file path.

    Returns
    -------
    str
        Destination path.
    """

    # Create destination directory if missing
    os.makedirs(os.path.dirname(dst), exist_ok=True)

    # Copy file
    shutil.copy2(src, dst)

    print(f"Copied file:")
    print(f"  From → {src}")
    print(f"  To   → {dst}")

    return dst


# =========================================================
# Extract Tar Archive
# =========================================================

def extract_tar(tar_path,
                extract_dir="/content/audio_data"):
    """
    Extract tar archive locally.

    Parameters
    ----------
    tar_path : str
        Tar archive path.

    extract_dir : str
        Directory where archive will be extracted.
    """

    # Create extraction directory
    os.makedirs(extract_dir, exist_ok=True)

    # Extract archive
    subprocess.run([
        "tar",
        "-xf",
        tar_path,
        "-C",
        extract_dir
    ], check=True)

    print(f"Extracted archive → {extract_dir}")


# =========================================================
# Load Archive + Update Manifests
# =========================================================

def load_archive_to_local(
    drive_tar_path,
    csv_paths,
    base_dir,
    local_tar_path="/content/data_archive.tar",
    extract_dir="/content/audio_data",
    local_manifest_dir="/content/local_manifests",
    path_col="seg_path"
):
    """
    Load compressed archive locally and prepare manifests.

    Workflow
    --------
    1. Copy archive from Drive
    2. Extract archive locally
    3. Update manifest paths
    4. Return local manifest paths

    Parameters
    ----------
    drive_tar_path : str
        Archive path stored in Drive.

    csv_paths : list
        Original CSV manifests.

    base_dir : str
        Original Drive data root.

    local_tar_path : str
        Temporary local tar path.

    extract_dir : str
        Local extraction directory.

    local_manifest_dir : str
        Directory where updated manifests will be saved.

    path_col : str
        Column containing audio paths.

    Returns
    -------
    list
        Updated local CSV manifest paths.
    """

    # -----------------------------------------------------
    # Copy archive locally
    # -----------------------------------------------------

    copy_file(
        src=drive_tar_path,
        dst=local_tar_path
    )

    # -----------------------------------------------------
    # Extract archive locally
    # -----------------------------------------------------

    extract_tar(
        tar_path=local_tar_path,
        extract_dir=extract_dir
    )

    # -----------------------------------------------------
    # Update manifests
    # -----------------------------------------------------

    os.makedirs(local_manifest_dir, exist_ok=True)

    local_csv_paths = []

    for csv_path in csv_paths:

        # Create local manifest name
        filename = os.path.basename(csv_path)

        out_csv_path = os.path.join(
            local_manifest_dir,
            filename.replace(".csv", "_local.csv")
        )

        # Update paths
        local_csv = update_manifest_paths(
            csv_path=csv_path,
            out_csv_path=out_csv_path,
            drive_base_dir=base_dir,
            local_base_dir=extract_dir,
            audio_col=path_col
        )

        local_csv_paths.append(local_csv)

    print("\nArchive loaded successfully.")
    print("Local manifests ready.")

    return local_csv_paths
