# -*- coding: utf-8 -*-
"""preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dCwsX3pk1HtJyrVkKA1tYUBK-QOJqQBs
"""

import os
import torch
import torchaudio
import librosa
import numpy as np
from silero_vad import load_silero_vad, get_speech_timestamps

# Load Silero VAD model once when the module is imported
silero_model = load_silero_vad()

# Target sampling rate used for all audio files
TARGET_SR = 16000


def load_audio(audio_path: str):
    """
    Load an audio file from disk.

    Parameters
    ----------
    audio_path : str
        Path to the audio file.

    Returns
    -------
    signal : torch.Tensor
        Audio waveform of shape [C, T].
    sr : int
        Original sampling rate of the audio file.
    """
    signal, sr = torchaudio.load(audio_path)
    return signal, sr


def to_mono(signal: torch.Tensor) -> torch.Tensor:
    """
    Convert multi-channel audio to mono by averaging channels.

    Parameters
    ----------
    signal : torch.Tensor
        Audio waveform of shape [C, T].

    Returns
    -------
    torch.Tensor
        Mono waveform of shape [T].
    """
    if signal.shape[0] > 1:
        signal = signal.mean(dim=0, keepdim=True)

    return signal.squeeze(0)


def resample_audio(wav: torch.Tensor, orig_sr: int, target_sr: int = TARGET_SR) -> torch.Tensor:
    """
    Resample an audio waveform to a fixed sampling rate.

    Parameters
    ----------
    wav : torch.Tensor
        Input waveform.
    orig_sr : int
        Original sampling rate.
    target_sr : int
        Target sampling rate.

    Returns
    -------
    torch.Tensor
        Resampled waveform.
    """
    if orig_sr != target_sr:
        resampler = torchaudio.transforms.Resample(orig_sr, target_sr)
        wav = resampler(wav.unsqueeze(0)).squeeze(0)

    return wav


def remove_leading_trailing_silence(wav: torch.Tensor, top_db: int = 30) -> torch.Tensor:
    """
    Remove leading and trailing silence from an audio waveform while preserving internal pauses.

    Parameters
    ----------
    wav : torch.Tensor
        Input waveform.
    top_db : int
        Threshold used for silence detection.

    Returns
    -------
    torch.Tensor
        Trimmed waveform with leading and trailing silence removed.
    """
    wav_np = wav.cpu().numpy()
    intervals = librosa.effects.split(wav_np, top_db=top_db)

    if len(intervals) == 0:
        return wav

    start = intervals[0][0]
    end = intervals[-1][1]
    trimmed = wav_np[start:end]

    return torch.tensor(trimmed, dtype=torch.float32)


def remove_internal_silence_vad(wav: torch.Tensor, sr: int = TARGET_SR) -> torch.Tensor:
    """
    Remove internal non-speech regions using Silero VAD.

    Parameters
    ----------
    wav : torch.Tensor
        Input waveform.
    sr : int
        Sampling rate of the audio.

    Returns
    -------
    torch.Tensor
        Waveform containing only speech regions.
    """
    wav = wav.float().cpu()

    speech_timestamps = get_speech_timestamps(
        wav,
        silero_model,
        sampling_rate=sr
    )

    if len(speech_timestamps) == 0:
        return torch.empty(0, dtype=torch.float32)

    speech_segments = [wav[item["start"]:item["end"]] for item in speech_timestamps]

    return torch.cat(speech_segments)


def segment_waveform(
    wav: torch.Tensor,
    sr: int = TARGET_SR,
    seg_sec: float = 3.0,
    hop_sec: float = 1.5
) -> torch.Tensor:
    """
    Split a waveform into overlapping fixed-length segments.

    Parameters
    ----------
    wav : torch.Tensor
        Input waveform.
    sr : int
        Sampling rate.
    seg_sec : float
        Length of each segment in seconds.
    hop_sec : float
        Step size between consecutive segments.

    Returns
    -------
    torch.Tensor
        Segmented waveform of shape [num_segments, segment_length].
    """
    seg_len = int(sr * seg_sec)
    hop_len = int(sr * hop_sec)

    if wav.numel() < seg_len:
        return torch.empty(0, dtype=torch.float32)

    frames = librosa.util.frame(
        wav.cpu().numpy(),
        frame_length=seg_len,
        hop_length=hop_len
    ).T

    return torch.from_numpy(frames.copy()).float()


def preprocess_audio(
    audio_path: str,
    target_sr: int = TARGET_SR,
    top_db: int = 30,
    seg_sec: float = 3.0,
    hop_sec: float = 1.5,
    remove_internal_silence: bool = False
) -> torch.Tensor:
    """
    Apply the complete audio preprocessing pipeline.

    Parameters
    ----------
    audio_path : str
        Path to the input audio file.
    target_sr : int
        Target sampling rate.
    top_db : int
        Silence detection threshold.
    seg_sec : float
        Segment length in seconds.
    hop_sec : float
        Step size between segments.
    remove_internal_silence : bool
        Whether to remove internal silence using VAD.

    Returns
    -------
    torch.Tensor
        Segmented audio ready for model input.
    """
    signal, sr = load_audio(audio_path)
    wav = to_mono(signal)
    wav = resample_audio(wav, sr, target_sr)
    wav = remove_leading_trailing_silence(wav, top_db=top_db)

    if remove_internal_silence:
        wav = remove_internal_silence_vad(wav, sr=target_sr)

    segments = segment_waveform(
        wav,
        sr=target_sr,
        seg_sec=seg_sec,
        hop_sec=hop_sec
    )

    return segments


def save_segments_as_wav(
    segments: torch.Tensor,
    output_dir: str,
    base_name: str,
    sr: int = TARGET_SR
):
    """
    Save segmented audio as individual .wav files.

    Parameters
    ----------
    segments : torch.Tensor
        Tensor of shape [num_segments, segment_length].
    output_dir : str
        Directory where the segments will be saved.
    base_name : str
        Base filename used to generate segment names.
    sr : int
        Sampling rate used when saving the audio.

    Returns
    -------
    None
    """
    os.makedirs(output_dir, exist_ok=True)

    for i, segment in enumerate(segments):

        if segment.ndim == 1:
            segment = segment.unsqueeze(0)

        output_path = os.path.join(output_dir, f"{base_name}_seg_{i}.wav")

        torchaudio.save(output_path, segment.cpu(), sr)


def load_segment_for_model(audio_path: str, target_sr: int = TARGET_SR) -> torch.Tensor:
    """
    Load a processed segment and prepare it for model input.

    Parameters
    ----------
    audio_path : str
        Path to the segment file.
    target_sr : int
        Target sampling rate.

    Returns
    -------
    torch.Tensor
        Preprocessed waveform ready for the model.
    """
    signal, sr = load_audio(audio_path)
    wav = to_mono(signal)
    wav = resample_audio(wav, sr, target_sr)
    return wav


def save_segment_as_wav(
    segment: torch.Tensor,
    output_path: str,
    sr: int = TARGET_SR
):
    """
    Save a single audio segment as a .wav file.

    Parameters
    ----------
    segment : torch.Tensor
        Audio waveform of shape [T] or [1, T].
    output_path : str
        Path where the .wav file will be saved.
    sr : int
        Sampling rate used when saving the audio.

    Returns
    -------
    None
    """
    if segment.ndim == 1:
        segment = segment.unsqueeze(0)

    torchaudio.save(output_path, segment.cpu(), sr)