# -*- coding: utf-8 -*-
"""preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dCwsX3pk1HtJyrVkKA1tYUBK-QOJqQBs
"""

# -*- coding: utf-8 -*-
"""
Audio Preprocessing Module

This module implements the audio preprocessing pipeline used for the
age verification experiments.

Supported datasets
------------------
1. Common Voice
   - Recordings may have different sampling rates.
   - Audio is resampled to 16 kHz.
   - Silence is removed from the beginning and end of the recording.

2. MyST
   - Audio is assumed to already use the target sampling rate.
   - Only silence trimming and segmentation are applied.

Processing Pipeline
-------------------
1. Load the audio recording.
2. Ensure the waveform is single-channel.
3. (Common Voice only) Resample audio to the target sampling rate.
4. Remove leading and trailing silence.
5. Optionally remove internal silence using voice activity detection.
6. Segment the waveform into fixed-length overlapping windows.

These segments are later used as inputs for the training pipeline.
"""

import os
import torch
import torchaudio
import librosa
from silero_vad import load_silero_vad, get_speech_timestamps


# =========================================================
# Global Configuration
# =========================================================

# Load the Silero VAD model once during import
silero_model = load_silero_vad()

# Target sampling rate used across the project
TARGET_SR = 16000


# =========================================================
# Basic Audio Utilities
# =========================================================
def load_audio(audio_path: str):
    """
    Load an audio file from disk.

    Parameters
    ----------
    audio_path : str
        Path to the audio file.

    Returns
    -------
    signal : torch.Tensor
        Audio waveform tensor.
    sr : int
        Sampling rate of the audio file.
    """
    signal, sr = torchaudio.load(audio_path)
    return signal, sr


def ensure_single_channel(signal: torch.Tensor) -> torch.Tensor:
    """
    Convert audio to a single-channel waveform.

    If the audio contains multiple channels, they are averaged to produce
    a mono waveform.

    Parameters
    ----------
    signal : torch.Tensor
        Input waveform tensor.

    Returns
    -------
    torch.Tensor
        Single-channel waveform.
    """
    if signal.ndim == 2 and signal.shape[0] > 1:
        signal = signal.mean(dim=0, keepdim=True)

    if signal.ndim == 2:
        return signal.squeeze(0)

    return signal


def resample_audio(
    wav: torch.Tensor,
    orig_sr: int,
    target_sr: int = TARGET_SR
) -> torch.Tensor:
    """
    Resample a waveform to the target sampling rate.

    Parameters
    ----------
    wav : torch.Tensor
        Input waveform.
    orig_sr : int
        Original sampling rate.
    target_sr : int
        Target sampling rate.

    Returns
    -------
    torch.Tensor
        Resampled waveform.
    """
    if orig_sr != target_sr:
        resampler = torchaudio.transforms.Resample(orig_sr, target_sr)
        wav = resampler(wav.unsqueeze(0)).squeeze(0)

    return wav


# =========================================================
# Silence Processing
# =========================================================
def remove_leading_trailing_silence(
    wav: torch.Tensor,
    top_db: int = 30
) -> torch.Tensor:
    """
    Remove silence from the beginning and end of a waveform.

    Internal pauses within the recording are preserved.

    Parameters
    ----------
    wav : torch.Tensor
        Input waveform.
    top_db : int
        Silence threshold in decibels.

    Returns
    -------
    torch.Tensor
        Trimmed waveform.
    """
    wav_np = wav.cpu().numpy()

    intervals = librosa.effects.split(wav_np, top_db=top_db)

    if len(intervals) == 0:
        return wav

    start = intervals[0][0]
    end = intervals[-1][1]

    trimmed = wav_np[start:end]

    return torch.tensor(trimmed, dtype=torch.float32)


def remove_internal_silence_vad(
    wav: torch.Tensor,
    sr: int = TARGET_SR
) -> torch.Tensor:
    """
    Remove internal non-speech regions using voice activity detection.

    Parameters
    ----------
    wav : torch.Tensor
        Input waveform.
    sr : int
        Sampling rate.

    Returns
    -------
    torch.Tensor
        Waveform containing only detected speech segments.
    """
    wav = wav.float().cpu()

    speech_timestamps = get_speech_timestamps(
        wav,
        silero_model,
        sampling_rate=sr
    )

    if len(speech_timestamps) == 0:
        return torch.empty(0, dtype=torch.float32)

    speech_segments = [
        wav[item["start"]:item["end"]]
        for item in speech_timestamps
    ]

    return torch.cat(speech_segments)


# =========================================================
# Segmentation
# =========================================================
def segment_waveform(
    wav: torch.Tensor,
    sr: int = TARGET_SR,
    seg_sec: float = 3.0,
    hop_sec: float = 1.5
) -> torch.Tensor:
    """
    Split a waveform into overlapping fixed-length segments.

    Parameters
    ----------
    wav : torch.Tensor
        Input waveform.
    sr : int
        Sampling rate.
    seg_sec : float
        Segment length in seconds.
    hop_sec : float
        Hop length in seconds.

    Returns
    -------
    torch.Tensor
        Tensor containing all generated segments.
    """
    seg_len = int(sr * seg_sec)
    hop_len = int(sr * hop_sec)

    if wav.numel() < seg_len:
        return torch.empty(0, dtype=torch.float32)

    frames = librosa.util.frame(
        wav.cpu().numpy(),
        frame_length=seg_len,
        hop_length=hop_len
    ).T

    return torch.from_numpy(frames.copy()).float()


# =========================================================
# Dataset-Specific Preprocessing
# =========================================================
def preprocess_common_voice_audio(
    audio_path: str,
    target_sr: int = TARGET_SR,
    top_db: int = 30,
    seg_sec: float = 3.0,
    hop_sec: float = 1.5,
    remove_internal_silence: bool = False
) -> torch.Tensor:
    """
    Apply preprocessing pipeline for Common Voice recordings.
    """

    signal, sr = load_audio(audio_path)

    wav = ensure_single_channel(signal).float()

    wav = resample_audio(wav, sr, target_sr)

    wav = remove_leading_trailing_silence(wav, top_db=top_db)

    if remove_internal_silence:
        wav = remove_internal_silence_vad(wav, sr=target_sr)

    if wav.numel() == 0:
        return torch.empty(0, dtype=torch.float32)

    return segment_waveform(
        wav,
        sr=target_sr,
        seg_sec=seg_sec,
        hop_sec=hop_sec
    )


def preprocess_myst_audio(
    audio_path: str,
    sr: int = TARGET_SR,
    top_db: int = 30,
    seg_sec: float = 3.0,
    hop_sec: float = 1.5,
    remove_internal_silence: bool = False
) -> torch.Tensor:
    """
    Apply preprocessing pipeline for MyST recordings.
    """

    signal, _ = load_audio(audio_path)

    wav = ensure_single_channel(signal).float()

    wav = remove_leading_trailing_silence(wav, top_db=top_db)

    if remove_internal_silence:
        wav = remove_internal_silence_vad(wav, sr=sr)

    if wav.numel() == 0:
        return torch.empty(0, dtype=torch.float32)

    return segment_waveform(
        wav,
        sr=sr,
        seg_sec=seg_sec,
        hop_sec=hop_sec
    )


# =========================================================
# Dispatcher
# =========================================================
def preprocess_by_dataset(
    audio_path: str,
    dataset_name: str,
    target_sr: int = TARGET_SR,
    top_db: int = 30,
    seg_sec: float = 3.0,
    hop_sec: float = 1.5,
    remove_internal_silence: bool = False
) -> torch.Tensor:
    """
    Select the appropriate preprocessing pipeline based on dataset name.
    """
    dataset_name = dataset_name.lower()

    if dataset_name == "cv":
        return preprocess_common_voice_audio(
            audio_path=audio_path,
            target_sr=target_sr,
            top_db=top_db,
            seg_sec=seg_sec,
            hop_sec=hop_sec,
            remove_internal_silence=remove_internal_silence
        )

    if dataset_name == "myst":
        return preprocess_myst_audio(
            audio_path=audio_path,
            sr=target_sr,
            top_db=top_db,
            seg_sec=seg_sec,
            hop_sec=hop_sec,
            remove_internal_silence=remove_internal_silence
        )

    raise ValueError(f"Unknown dataset_name: {dataset_name}")


# =========================================================
# Model Input Utility
# =========================================================
def load_segment_for_model(
    audio_path: str,
    target_sr: int = TARGET_SR
) -> torch.Tensor:
    """
    Load a saved audio segment and prepare it for model input.
    """
    signal, sr = load_audio(audio_path)

    wav = ensure_single_channel(signal).float()

    wav = resample_audio(wav, sr, target_sr)

    return wav


# =========================================================
# Segment Saving
# =========================================================
def save_segment_as_wav(
    segment: torch.Tensor,
    output_path: str,
    sr: int = TARGET_SR
):
    """
    Save a single audio segment to disk as a WAV file.
    """

    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    if segment.ndim == 1:
        segment = segment.unsqueeze(0)

    torchaudio.save(output_path, segment.cpu(), sr)