{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/ArwaFadaaq/Robust-Multimodal-Age-Verification-for-Online-Gaming-Chat/blob/main/preprocessing.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# -*- coding: utf-8 -*-\n",
        "\"\"\"\n",
        "Audio preprocessing utilities for age verification experiments.\n",
        "\n",
        "Pipeline summary\n",
        "----------------\n",
        "Common Voice:\n",
        "    load -> ensure single channel -> resample to 16 kHz\n",
        "    -> trim leading/trailing silence\n",
        "    -> optional internal silence removal\n",
        "    -> segmentation\n",
        "\n",
        "MyST:\n",
        "    load -> ensure single channel\n",
        "    -> trim leading/trailing silence\n",
        "    -> optional internal silence removal\n",
        "    -> segmentation\n",
        "\"\"\"\n",
        "\n",
        "import os\n",
        "import torch\n",
        "import torchaudio\n",
        "import librosa\n",
        "from silero_vad import load_silero_vad, get_speech_timestamps\n",
        "\n",
        "# Load Silero VAD once at import time\n",
        "silero_model = load_silero_vad()\n",
        "\n",
        "# Default target sampling rate\n",
        "TARGET_SR = 16000\n",
        "\n",
        "\n",
        "def load_audio(audio_path: str):\n",
        "    \"\"\"Load an audio file and return waveform and sampling rate.\"\"\"\n",
        "    signal, sr = torchaudio.load(audio_path)\n",
        "    return signal, sr\n",
        "\n",
        "\n",
        "def ensure_single_channel(signal: torch.Tensor) -> torch.Tensor:\n",
        "    \"\"\"Return a 1D waveform, with a safety check for multi-channel audio.\"\"\"\n",
        "    if signal.ndim == 2 and signal.shape[0] > 1:\n",
        "        signal = signal.mean(dim=0, keepdim=True)\n",
        "\n",
        "    if signal.ndim == 2:\n",
        "        return signal.squeeze(0)\n",
        "\n",
        "    return signal\n",
        "\n",
        "\n",
        "def resample_audio(\n",
        "    wav: torch.Tensor,\n",
        "    orig_sr: int,\n",
        "    target_sr: int = TARGET_SR\n",
        ") -> torch.Tensor:\n",
        "    \"\"\"Resample a waveform if needed.\"\"\"\n",
        "    if orig_sr != target_sr:\n",
        "        resampler = torchaudio.transforms.Resample(orig_sr, target_sr)\n",
        "        wav = resampler(wav.unsqueeze(0)).squeeze(0)\n",
        "    return wav\n",
        "\n",
        "\n",
        "def remove_leading_trailing_silence(\n",
        "    wav: torch.Tensor,\n",
        "    top_db: int = 30\n",
        ") -> torch.Tensor:\n",
        "    \"\"\"Trim leading and trailing silence while keeping internal pauses.\"\"\"\n",
        "    wav_np = wav.cpu().numpy()\n",
        "    intervals = librosa.effects.split(wav_np, top_db=top_db)\n",
        "\n",
        "    if len(intervals) == 0:\n",
        "        return wav\n",
        "\n",
        "    start = intervals[0][0]\n",
        "    end = intervals[-1][1]\n",
        "    trimmed = wav_np[start:end]\n",
        "\n",
        "    return torch.tensor(trimmed, dtype=torch.float32)\n",
        "\n",
        "\n",
        "def remove_internal_silence_vad(\n",
        "    wav: torch.Tensor,\n",
        "    sr: int = TARGET_SR\n",
        ") -> torch.Tensor:\n",
        "    \"\"\"Remove internal non-speech regions using Silero VAD.\"\"\"\n",
        "    wav = wav.float().cpu()\n",
        "\n",
        "    speech_timestamps = get_speech_timestamps(\n",
        "        wav,\n",
        "        silero_model,\n",
        "        sampling_rate=sr\n",
        "    )\n",
        "\n",
        "    if len(speech_timestamps) == 0:\n",
        "        return torch.empty(0, dtype=torch.float32)\n",
        "\n",
        "    speech_segments = [\n",
        "        wav[item[\"start\"]:item[\"end\"]]\n",
        "        for item in speech_timestamps\n",
        "    ]\n",
        "\n",
        "    return torch.cat(speech_segments)\n",
        "\n",
        "\n",
        "def segment_waveform(\n",
        "    wav: torch.Tensor,\n",
        "    sr: int = TARGET_SR,\n",
        "    seg_sec: float = 3.0,\n",
        "    hop_sec: float = 1.5\n",
        ") -> torch.Tensor:\n",
        "    \"\"\"Split a waveform into overlapping fixed-length segments.\"\"\"\n",
        "    seg_len = int(sr * seg_sec)\n",
        "    hop_len = int(sr * hop_sec)\n",
        "\n",
        "    if wav.numel() < seg_len:\n",
        "        return torch.empty(0, dtype=torch.float32)\n",
        "\n",
        "    frames = librosa.util.frame(\n",
        "        wav.cpu().numpy(),\n",
        "        frame_length=seg_len,\n",
        "        hop_length=hop_len\n",
        "    ).T\n",
        "\n",
        "    return torch.from_numpy(frames.copy()).float()\n",
        "\n",
        "\n",
        "def preprocess_common_voice_audio(\n",
        "    audio_path: str,\n",
        "    target_sr: int = TARGET_SR,\n",
        "    top_db: int = 30,\n",
        "    seg_sec: float = 3.0,\n",
        "    hop_sec: float = 1.5,\n",
        "    remove_internal_silence: bool = False\n",
        ") -> torch.Tensor:\n",
        "    \"\"\"Preprocess a Common Voice recording into fixed-length segments.\"\"\"\n",
        "\n",
        "    # Load audio\n",
        "    signal, sr = load_audio(audio_path)\n",
        "\n",
        "    # Ensure a 1D waveform\n",
        "    wav = ensure_single_channel(signal).float()\n",
        "\n",
        "    # Resample Common Voice audio to the target sampling rate\n",
        "    wav = resample_audio(wav, sr, target_sr)\n",
        "\n",
        "    # Remove leading and trailing silence only\n",
        "    wav = remove_leading_trailing_silence(wav, top_db=top_db)\n",
        "\n",
        "    # Optional ablation: remove internal non-speech regions\n",
        "    if remove_internal_silence:\n",
        "        wav = remove_internal_silence_vad(wav, sr=target_sr)\n",
        "\n",
        "    if wav.numel() == 0:\n",
        "        return torch.empty(0, dtype=torch.float32)\n",
        "\n",
        "    # Split into overlapping fixed-length segments\n",
        "    return segment_waveform(\n",
        "        wav,\n",
        "        sr=target_sr,\n",
        "        seg_sec=seg_sec,\n",
        "        hop_sec=hop_sec\n",
        "    )\n",
        "\n",
        "\n",
        "def preprocess_myst_audio(\n",
        "    audio_path: str,\n",
        "    sr: int = TARGET_SR,\n",
        "    top_db: int = 30,\n",
        "    seg_sec: float = 3.0,\n",
        "    hop_sec: float = 1.5,\n",
        "    remove_internal_silence: bool = False\n",
        ") -> torch.Tensor:\n",
        "    \"\"\"Preprocess a MyST recording into fixed-length segments.\"\"\"\n",
        "\n",
        "    # Load audio\n",
        "    signal, _ = load_audio(audio_path)\n",
        "\n",
        "    # Ensure a 1D waveform\n",
        "    wav = ensure_single_channel(signal).float()\n",
        "\n",
        "    # MyST is assumed to already use the desired sampling rate\n",
        "    wav = remove_leading_trailing_silence(wav, top_db=top_db)\n",
        "\n",
        "    # Optional ablation: remove internal non-speech regions\n",
        "    if remove_internal_silence:\n",
        "        wav = remove_internal_silence_vad(wav, sr=sr)\n",
        "\n",
        "    if wav.numel() == 0:\n",
        "        return torch.empty(0, dtype=torch.float32)\n",
        "\n",
        "    # Split into overlapping fixed-length segments\n",
        "    return segment_waveform(\n",
        "        wav,\n",
        "        sr=sr,\n",
        "        seg_sec=seg_sec,\n",
        "        hop_sec=hop_sec\n",
        "    )\n",
        "\n",
        "\n",
        "def preprocess_by_dataset(\n",
        "    audio_path: str,\n",
        "    dataset_name: str,\n",
        "    target_sr: int = TARGET_SR,\n",
        "    top_db: int = 30,\n",
        "    seg_sec: float = 3.0,\n",
        "    hop_sec: float = 1.5,\n",
        "    remove_internal_silence: bool = False\n",
        ") -> torch.Tensor:\n",
        "    \"\"\"Dispatch preprocessing based on dataset name.\"\"\"\n",
        "    dataset_name = dataset_name.lower()\n",
        "\n",
        "    if dataset_name == \"cv\":\n",
        "        return preprocess_common_voice_audio(\n",
        "            audio_path=audio_path,\n",
        "            target_sr=target_sr,\n",
        "            top_db=top_db,\n",
        "            seg_sec=seg_sec,\n",
        "            hop_sec=hop_sec,\n",
        "            remove_internal_silence=remove_internal_silence\n",
        "        )\n",
        "\n",
        "    if dataset_name == \"myst\":\n",
        "        return preprocess_myst_audio(\n",
        "            audio_path=audio_path,\n",
        "            sr=target_sr,\n",
        "            top_db=top_db,\n",
        "            seg_sec=seg_sec,\n",
        "            hop_sec=hop_sec,\n",
        "            remove_internal_silence=remove_internal_silence\n",
        "        )\n",
        "\n",
        "    raise ValueError(f\"Unknown dataset_name: {dataset_name}\")\n",
        "\n",
        "\n",
        "def load_segment_for_model(\n",
        "    audio_path: str,\n",
        "    target_sr: int = TARGET_SR\n",
        ") -> torch.Tensor:\n",
        "    \"\"\"Load a saved segment and prepare it for model input.\"\"\"\n",
        "    signal, sr = load_audio(audio_path)\n",
        "    wav = ensure_single_channel(signal).float()\n",
        "    wav = resample_audio(wav, sr, target_sr)\n",
        "    return wav\n",
        "\n",
        "\n",
        "def save_segment_as_wav(\n",
        "    segment: torch.Tensor,\n",
        "    output_path: str,\n",
        "    sr: int = TARGET_SR\n",
        "):\n",
        "    \"\"\"Save a single audio segment as a WAV file.\"\"\"\n",
        "    os.makedirs(os.path.dirname(output_path), exist_ok=True)\n",
        "\n",
        "    if segment.ndim == 1:\n",
        "        segment = segment.unsqueeze(0)\n",
        "\n",
        "    torchaudio.save(output_path, segment.cpu(), sr)"
      ],
      "metadata": {
        "id": "lnZZ6vOT0IbF"
      },
      "execution_count": null,
      "outputs": []
    }
  ],
  "metadata": {
    "colab": {
      "provenance": [],
      "include_colab_link": true
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}