# -*- coding: utf-8 -*-
"""speaker_split_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UlxHQ3-tmA78oN9gVYhG-xbadFssruVL
"""

"""
Speaker-Level Stratified Splitting Pipeline
------------------------------------------

This module implements a speaker-disjoint stratified data splitting pipeline
for audio-based datasets.

Objective
---------
To partition datasets into training, validation, and test splits while:
- Preventing speaker overlap across splits (no data leakage).
- Preserving key data distributions (e.g., dataset source, gender, and age).

Methodology
-----------
1. Clean and normalize metadata fields.
2. Derive auxiliary features (e.g., age_bin) for stratification.
3. Construct a stratification key based on dataset type:
   - Adult datasets: (dataset_source, gender, age_bin)
   - Minor datasets: (dataset_source, gender)
4. Perform stratified splitting at the speaker level.
5. Assign speakers to train/val/test splits according to predefined ratios.
6. Validate that no speaker appears in multiple splits.

Output
------
- A CSV file per dataset containing:
  - Original metadata
  - Assigned split label (train / val / test)

Notes
-----
- Auxiliary columns (e.g., strat_key, age_bin) are used internally
  during processing and are removed before saving the final output.
- The pipeline is deterministic given a fixed random seed.
"""

import os
import numpy as np
import pandas as pd


# ─── Column Cleaning ─────────────────────────────────────
def clean_col(df: pd.DataFrame, col: str, fill_value: str = "unknown") -> pd.DataFrame:
    """
    Standardize a metadata column by:
    1. Replacing missing values with a default label.
    2. Converting values to string format.
    3. Removing leading/trailing whitespace.

    This ensures consistency before downstream processing.
    """
    if col in df.columns:
        df[col] = df[col].astype(object).where(~df[col].isna(), fill_value)
        df[col] = df[col].astype(str).str.strip()
    return df


# ─── Age Mapping ─────────────────────────────────────────
def map_age_to_bin(age) -> str:
    """
    Map raw age values into unified categorical bins.

    Supported bins:
    - twenties, thirties, fourties, fifties, sixties, 70+

    Handles both string labels and numeric ages.
    """
    age = str(age).strip().lower()

    if age in ["twenties", "thirties", "fourties", "fifties", "sixties"]:
        return age
    if age in ["seventies", "eighties", "nineties"]:
        return "70+"

    try:
        age_num = int(float(age))
        if age_num < 30:
            return "twenties"
        elif age_num < 40:
            return "thirties"
        elif age_num < 50:
            return "fourties"
        elif age_num < 60:
            return "fifties"
        elif age_num < 70:
            return "sixties"
        else:
            return "70+"
    except Exception:
        return "unknown"


# ─── Data Cleaning Pipeline ──────────────────────────────
def clean_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    """
    Validate and normalize the speaker-level dataset.

    Key steps:
    - Ensure required column (speaker_id) exists.
    - Normalize metadata fields (dataset_source, gender, age).
    - Generate age_bin for consistent grouping.
    """
    df = df.copy()

    if "speaker_id" not in df.columns:
        raise ValueError("Missing required column: speaker_id")

    df["speaker_id"] = df["speaker_id"].astype(str).str.strip()

    for col in ["dataset_source", "gender", "source_age"]:
        if col in df.columns:
            df = clean_col(df, col, fill_value="unknown")

    if "source_age" in df.columns:
        df["age_bin"] = df["source_age"].apply(map_age_to_bin)

    return df


# ─── Stratification Key ──────────────────────────────────
def build_strat_key(speakers_df: pd.DataFrame, dataset_name: str) -> pd.Series:
    """
    Construct a stratification key used to preserve data distribution
    across splits.

    Adult datasets → stratify by (dataset_source, gender, age_bin)
    Minor datasets → stratify by (dataset_source, gender)
    """
    speakers_df = speakers_df.copy()

    if "dataset_source" not in speakers_df.columns:
        raise ValueError(f"{dataset_name}: missing column 'dataset_source'")

    speakers_df = clean_col(speakers_df, "dataset_source", "unknown")
    speakers_df = clean_col(speakers_df, "gender", "unknown")
    speakers_df = clean_col(speakers_df, "source_age", "unknown")

    if dataset_name in ["adult_real_candidates", "adult_spoof_targets"]:
        if "age_bin" not in speakers_df.columns:
            raise ValueError(f"{dataset_name}: missing column 'age_bin'")
        return (
            speakers_df["dataset_source"] + "|" +
            speakers_df["gender"] + "|" +
            speakers_df["age_bin"]
        )

    elif dataset_name in ["minor_real_candidates", "minor_spoof_targets"]:
        return (
            speakers_df["dataset_source"] + "|" +
            speakers_df["gender"]
        )

    else:
        raise ValueError(f"Unknown dataset name: {dataset_name}")


# ─── Split Size Assignment ───────────────────────────────
def assign_counts(
    n: int,
    train_ratio: float = 0.70,
    val_ratio: float = 0.15,
    rng: np.random.Generator | None = None
) -> tuple[int, int, int]:
    """
    Determine the number of samples assigned to each split
    within a single stratum.

    - Uses probabilistic assignment for small groups.
    - Uses proportional allocation with rounding correction otherwise.
    """
    if n <= 0:
        return 0, 0, 0

    if n <= 5:
        probs = [train_ratio, val_ratio, 1 - train_ratio - val_ratio]
        choices = rng.choice(["train", "val", "test"], size=n, p=probs)
        return (
            (choices == "train").sum(),
            (choices == "val").sum(),
            (choices == "test").sum()
        )

    target_train = n * train_ratio
    target_val   = n * val_ratio
    target_test  = n - target_train - target_val

    n_train = int(np.floor(target_train))
    n_val   = int(np.floor(target_val))
    n_test  = int(np.floor(target_test))

    remaining = n - (n_train + n_val + n_test)

    remainders = [
        ("train", target_train - n_train),
        ("val",   target_val - n_val),
        ("test",  target_test - n_test),
    ]

    rng.shuffle(remainders)
    remainders.sort(key=lambda x: x[1], reverse=True)

    for i in range(remaining):
        if remainders[i][0] == "train":
            n_train += 1
        elif remainders[i][0] == "val":
            n_val += 1
        else:
            n_test += 1

    return n_train, n_val, n_test


# ─── Speaker-Disjoint Split ──────────────────────────────
def speaker_disjoint_stratified_split(
    df: pd.DataFrame,
    dataset_name: str,
    train_ratio: float = 0.70,
    val_ratio: float = 0.15,
    seed: int = 42
) -> pd.DataFrame:
    """
    Perform a stratified split while ensuring:
    - No speaker appears in more than one split.
    - Data distribution is preserved across splits.
    """
    rng = np.random.default_rng(seed)
    df = clean_dataframe(df)

    speakers = df.copy()
    speakers["strat_key"] = build_strat_key(speakers, dataset_name)
    speakers["split"] = ""

    for _, grp in speakers.groupby("strat_key", sort=False):
        speaker_ids = grp["speaker_id"].tolist()
        rng.shuffle(speaker_ids)

        n_train, n_val, n_test = assign_counts(
            n=len(speaker_ids),
            train_ratio=train_ratio,
            val_ratio=val_ratio,
            rng=rng
        )

        speakers.loc[speakers["speaker_id"].isin(speaker_ids[:n_train]), "split"] = "train"
        speakers.loc[speakers["speaker_id"].isin(speaker_ids[n_train:n_train+n_val]), "split"] = "val"
        speakers.loc[speakers["speaker_id"].isin(speaker_ids[n_train+n_val:]), "split"] = "test"

    if (speakers["split"] == "").any():
        raise ValueError(f"{dataset_name}: unassigned speakers detected")

    return speakers


# ─── Split Validation ────────────────────────────────────
def report_split_stats(split_df: pd.DataFrame, dataset_name: str) -> None:
    """
    Verify split integrity and report distribution.

    Checks:
    - No overlap between splits (no speaker leakage).
    - Displays counts and percentages.
    """
    sp = split_df.copy()

    train_speakers = set(sp.loc[sp["split"] == "train", "speaker_id"])
    val_speakers   = set(sp.loc[sp["split"] == "val", "speaker_id"])
    test_speakers  = set(sp.loc[sp["split"] == "test", "speaker_id"])

    if (train_speakers & val_speakers) or \
       (train_speakers & test_speakers) or \
       (val_speakers & test_speakers):
        raise ValueError(f"{dataset_name}: speaker leakage detected")

    total = len(sp)
    print("\nSpeaker counts:")
    for s in ["train", "val", "test"]:
        n = (sp["split"] == s).sum()
        print(f"{s}: {n} ({(n/total)*100:.2f}%)")


# ─── Save Results ────────────────────────────────────────
def save_inventory_with_split(split_df, dataset_name, out_dir):
    """
    Save the processed dataset with assigned splits.
    """
    os.makedirs(out_dir, exist_ok=True)

    cols_to_drop = ["strat_key", "age_bin"]
    split_df = split_df.drop(columns=[c for c in cols_to_drop if c in split_df.columns])

    path = os.path.join(out_dir, f"{dataset_name}_split.csv")
    split_df.to_csv(path, index=False)
    return path


# ─── Full Pipeline ───────────────────────────────────────
def run_speaker_split_pipeline(input_files, output_dir, train_ratio=0.70, val_ratio=0.15, seed=42):
    """
    Execute the complete pipeline:
    - Load dataset
    - Perform speaker-disjoint stratified split
    - Validate results
    - Save outputs
    """
    os.makedirs(output_dir, exist_ok=True)

    for dataset_name, file_path in input_files.items():
        print("=" * 78)
        print(f"\nProcessing: {dataset_name}")
        print("=" * 78)

        df = pd.read_csv(file_path)
        split_df = speaker_disjoint_stratified_split(df, dataset_name, train_ratio, val_ratio, seed)

        report_split_stats(split_df, dataset_name)
        save_inventory_with_split(split_df, dataset_name, output_dir)
