# -*- coding: utf-8 -*-
"""speaker_split_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UlxHQ3-tmA78oN9gVYhG-xbadFssruVL
"""

"""
Speaker-Level Stratified Splitting Pipeline
------------------------------------------

This module implements two speaker-level splitting utilities for audio-based
datasets.

Objectives
----------
1. Speaker-Level Stratified Splitting:
   Partition datasets into training, validation, and test splits while:
   - Preventing speaker overlap across splits (no data leakage).
   - Preserving key data distributions such as dataset source, gender, and age.

2. Split Half - Speaker-Level Balanced Splitting:
   Partition an existing split dataframe into two balanced halves (A and B) while:
   - Ensuring no speaker appears in both halves.
   - Balancing speaker counts between the two halves.
   - Balancing segment counts between the two halves.
   - Preserving age class distribution.
   - Preserving source and gender diversity when available.

Methodology
-----------
Part 1: Speaker-Level Stratified Splitting
1. Clean and normalize metadata fields.
2. Derive auxiliary features such as age_bin for stratification.
3. Construct a stratification key based on dataset type:
   - Adult datasets: (dataset_source, gender, age_bin)
   - Minor datasets: (dataset_source, gender)
4. Perform stratified splitting at the speaker level.
5. Assign speakers to train/val/test splits according to predefined ratios.
6. Validate that no speaker appears in multiple splits.

Part 2: Split Half - Speaker-Level Balanced Splitting
1. Build a speaker-level summary containing:
   - Number of segments per speaker.
   - Age class.
   - Dataset source, if available.
   - Gender, if available.
2. Try multiple random 50/50 speaker partitions using GroupShuffleSplit.
3. Score each partition based on:
   - Speaker count difference between A and B.
   - Segment count difference between A and B.
   - Age class distribution difference between A and B.
   - Source diversity penalty, if dataset_source is available.
   - Gender diversity penalty, if gender is available.
4. Select the partition with the lowest combined score.
5. Save both halves as CSV files.

Outputs
-------
Part 1:
- A CSV file per dataset containing:
  - Original metadata.
  - Assigned split label: train / val / test.

Part 2:
- {output_dir}/{split_name}_real_A.csv
- {output_dir}/{split_name}_real_B.csv

Notes
-----
- All splitting is performed at the speaker level to prevent data leakage.
- Auxiliary columns such as strat_key and age_bin are used internally and removed
  before saving final outputs.
- The pipeline is deterministic given a fixed random seed.
- Split Half is useful after creating train/val/test splits when an additional
  balanced A/B division is needed for real data.
"""
import os
import numpy as np
import pandas as pd

from sklearn.model_selection import GroupShuffleSplit

# ─── Column Cleaning ─────────────────────────────────────
def clean_col(df: pd.DataFrame, col: str, fill_value: str = "unknown") -> pd.DataFrame:
    """
    Standardize a metadata column by:
    1. Replacing missing values with a default label.
    2. Converting values to string format.
    3. Removing leading/trailing whitespace.

    This ensures consistency before downstream processing.
    """
    if col in df.columns:
        df[col] = df[col].astype(object).where(~df[col].isna(), fill_value)
        df[col] = df[col].astype(str).str.strip()
    return df

# ─── Age Mapping ─────────────────────────────────────────
def map_age_to_bin(age) -> str:
    """
    Map raw age values into unified categorical bins.

    Supported bins:
    - twenties, thirties, fourties, fifties, sixties, 70+

    Handles both string labels and numeric ages.
    """
    age = str(age).strip().lower()

    if age in ["twenties", "thirties", "fourties", "fifties", "sixties"]:
        return age
    if age in ["seventies", "eighties", "nineties"]:
        return "70+"

    try:
        age_num = int(float(age))
        if age_num < 30:
            return "twenties"
        elif age_num < 40:
            return "thirties"
        elif age_num < 50:
            return "fourties"
        elif age_num < 60:
            return "fifties"
        elif age_num < 70:
            return "sixties"
        else:
            return "70+"
    except Exception:
        return "unknown"


# ─── Data Cleaning Pipeline ──────────────────────────────
def clean_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    """
    Validate and normalize the speaker-level dataset.

    Key steps:
    - Ensure required column (speaker_id) exists.
    - Normalize metadata fields (dataset_source, gender, age).
    - Generate age_bin for consistent grouping.
    """
    df = df.copy()

    if "speaker_id" not in df.columns:
        raise ValueError("Missing required column: speaker_id")

    df["speaker_id"] = df["speaker_id"].astype(str).str.strip()

    for col in ["dataset_source", "gender", "source_age"]:
        if col in df.columns:
            df = clean_col(df, col, fill_value="unknown")

    if "source_age" in df.columns:
        df["age_bin"] = df["source_age"].apply(map_age_to_bin)

    return df


# ─── Stratification Key ──────────────────────────────────
def build_strat_key(speakers_df: pd.DataFrame, dataset_name: str) -> pd.Series:
    """
    Construct a stratification key used to preserve data distribution
    across splits.

    Adult datasets → stratify by (dataset_source, gender, age_bin)
    Minor datasets → stratify by (dataset_source, gender)
    """
    speakers_df = speakers_df.copy()

    if "dataset_source" not in speakers_df.columns:
        raise ValueError(f"{dataset_name}: missing column 'dataset_source'")

    speakers_df = clean_col(speakers_df, "dataset_source", "unknown")
    speakers_df = clean_col(speakers_df, "gender", "unknown")
    speakers_df = clean_col(speakers_df, "source_age", "unknown")

    if dataset_name in ["adult_real_candidates", "adult_spoof_targets", "adult_backup"]:
        if "age_bin" not in speakers_df.columns:
            raise ValueError(f"{dataset_name}: missing column 'age_bin'")
        return (
            speakers_df["dataset_source"] + "|" +
            speakers_df["gender"] + "|" +
            speakers_df["age_bin"]
        )

    elif dataset_name in ["minor_real_candidates", "minor_spoof_targets", "minor_backup"]:
        return (
            speakers_df["dataset_source"] + "|" +
            speakers_df["gender"]
        )

    else:
        raise ValueError(f"Unknown dataset name: {dataset_name}")


# ─── Split Size Assignment ───────────────────────────────
def assign_counts(
    n: int,
    train_ratio: float = 0.70,
    val_ratio: float = 0.15,
    rng: np.random.Generator | None = None
) -> tuple[int, int, int]:
    """
    Determine the number of samples assigned to each split
    within a single stratum.

    - Uses probabilistic assignment for small groups.
    - Uses proportional allocation with rounding correction otherwise.
    """
    if n <= 0:
        return 0, 0, 0

    if n <= 5:
        probs = [train_ratio, val_ratio, 1 - train_ratio - val_ratio]
        choices = rng.choice(["train", "val", "test"], size=n, p=probs)
        return (
            (choices == "train").sum(),
            (choices == "val").sum(),
            (choices == "test").sum()
        )

    target_train = n * train_ratio
    target_val   = n * val_ratio
    target_test  = n - target_train - target_val

    n_train = int(np.floor(target_train))
    n_val   = int(np.floor(target_val))
    n_test  = int(np.floor(target_test))

    remaining = n - (n_train + n_val + n_test)

    remainders = [
        ("train", target_train - n_train),
        ("val",   target_val - n_val),
        ("test",  target_test - n_test),
    ]

    rng.shuffle(remainders)
    remainders.sort(key=lambda x: x[1], reverse=True)

    for i in range(remaining):
        if remainders[i][0] == "train":
            n_train += 1
        elif remainders[i][0] == "val":
            n_val += 1
        else:
            n_test += 1

    return n_train, n_val, n_test


# ─── Speaker-Disjoint Split ──────────────────────────────
def speaker_disjoint_stratified_split(
    df: pd.DataFrame,
    dataset_name: str,
    train_ratio: float = 0.70,
    val_ratio: float = 0.15,
    seed: int = 42
) -> pd.DataFrame:
    """
    Perform a stratified split while ensuring:
    - No speaker appears in more than one split.
    - Data distribution is preserved across splits.
    """
    rng = np.random.default_rng(seed)
    df = clean_dataframe(df)

    speakers = df.copy()
    speakers["strat_key"] = build_strat_key(speakers, dataset_name)
    speakers["split"] = ""

    for _, grp in speakers.groupby("strat_key", sort=False):
        speaker_ids = grp["speaker_id"].tolist()
        rng.shuffle(speaker_ids)

        n_train, n_val, n_test = assign_counts(
            n=len(speaker_ids),
            train_ratio=train_ratio,
            val_ratio=val_ratio,
            rng=rng
        )

        speakers.loc[speakers["speaker_id"].isin(speaker_ids[:n_train]), "split"] = "train"
        speakers.loc[speakers["speaker_id"].isin(speaker_ids[n_train:n_train+n_val]), "split"] = "val"
        speakers.loc[speakers["speaker_id"].isin(speaker_ids[n_train+n_val:]), "split"] = "test"

    if (speakers["split"] == "").any():
        raise ValueError(f"{dataset_name}: unassigned speakers detected")

    return speakers


# ─── Split Validation ────────────────────────────────────
def report_split_stats(split_df: pd.DataFrame, dataset_name: str) -> None:
    """
    Verify split integrity and report distribution.

    Checks:
    - No overlap between splits (no speaker leakage).
    - Displays counts and percentages.
    """
    sp = split_df.copy()

    train_speakers = set(sp.loc[sp["split"] == "train", "speaker_id"])
    val_speakers   = set(sp.loc[sp["split"] == "val", "speaker_id"])
    test_speakers  = set(sp.loc[sp["split"] == "test", "speaker_id"])

    if (train_speakers & val_speakers) or \
       (train_speakers & test_speakers) or \
       (val_speakers & test_speakers):
        raise ValueError(f"{dataset_name}: speaker leakage detected")

    total = len(sp)
    print("\nSpeaker counts:")
    for s in ["train", "val", "test"]:
        n = (sp["split"] == s).sum()
        print(f"{s}: {n} ({(n/total)*100:.2f}%)")


# ─── Save Results ────────────────────────────────────────
def save_inventory_with_split(split_df, dataset_name, out_dir):
    """
    Save the processed dataset with assigned splits.
    """
    os.makedirs(out_dir, exist_ok=True)

    cols_to_drop = ["strat_key", "age_bin"]
    split_df = split_df.drop(columns=[c for c in cols_to_drop if c in split_df.columns])

    path = os.path.join(out_dir, f"{dataset_name}_split.csv")
    split_df.to_csv(path, index=False)
    return path


# ─── Full Pipeline ───────────────────────────────────────
def run_speaker_split_pipeline(input_files, output_dir, train_ratio=0.70, val_ratio=0.15, seed=42):
    """
    Execute the complete pipeline:
    - Load dataset
    - Perform speaker-disjoint stratified split
    - Validate results
    - Save outputs
    """
    os.makedirs(output_dir, exist_ok=True)

    for dataset_name, file_path in input_files.items():
        print("\n" + "=" * 60)
        print(f"Processing: {dataset_name}")
        print("=" * 60)

        df = pd.read_csv(file_path, dtype={"speaker_id": str})
        df["speaker_id"] = df["speaker_id"].astype(str).str.strip()

        if "dataset_source" in df.columns:
            myst_mask = df["dataset_source"] == "myst"
            df.loc[myst_mask, "speaker_id"] = df.loc[myst_mask, "speaker_id"].str.zfill(6)

        split_df = speaker_disjoint_stratified_split(df, dataset_name, train_ratio, val_ratio, seed)

        report_split_stats(split_df, dataset_name)
        save_inventory_with_split(split_df, dataset_name, output_dir)

# ─── Split Half ──────────────────────────────────────────
def split_half(df, split_name, output_dir, n_splits=200, seed=42):
    # Build speaker-level summary
    agg_dict = {
        "n_segments": ("speaker_id", "size"),
        "mapped_age_class": ("mapped_age_class", "first"),
    }
    if "dataset_source" in df.columns:
        agg_dict["dataset_source"] = ("dataset_source", "first")
    if "gender" in df.columns:
        agg_dict["gender"] = ("gender", "first")

    speaker_info = (
        df.groupby("speaker_id")
        .agg(**agg_dict)
        .reset_index()
    )

    # Try n_splits random 50/50 speaker splits and pick the best one
    gss = GroupShuffleSplit(n_splits=n_splits, test_size=0.5, random_state=seed)
    best_score = float("inf")
    best_a_speakers = None
    best_b_speakers = None

    for a_idx, b_idx in gss.split(speaker_info, groups=speaker_info["speaker_id"]):
        a = speaker_info.iloc[a_idx]
        b = speaker_info.iloc[b_idx]

        # Criterion 1: speaker count balance
        spk_diff = abs(len(a) - len(b))

        # Criterion 2: segment count balance
        seg_diff = abs(a["n_segments"].sum() - b["n_segments"].sum())

        # Criterion 3: age class distribution balance
        a_age = a["mapped_age_class"].value_counts(normalize=True)
        b_age = b["mapped_age_class"].value_counts(normalize=True)
        all_ages = set(a_age.index) | set(b_age.index)
        age_diff = sum(abs(a_age.get(v, 0) - b_age.get(v, 0)) for v in all_ages)

        # Criterion 4: source diversity check
        a_sources = a["dataset_source"].nunique() if "dataset_source" in a.columns else 1
        b_sources = b["dataset_source"].nunique() if "dataset_source" in b.columns else 1

        # Criterion 5: gender diversity check
        a_genders = a["gender"].nunique() if "gender" in a.columns else 1
        b_genders = b["gender"].nunique() if "gender" in b.columns else 1

        # Penalize splits dominated by only one source or gender
        diversity_penalty = 0
        if a_sources < 2:
            diversity_penalty += 10000
        if b_sources < 2:
            diversity_penalty += 10000
        if a_genders < 2:
            diversity_penalty += 5000
        if b_genders < 2:
            diversity_penalty += 5000

        # Combined score
        score = (
            spk_diff * 1000 +
            age_diff * 500 +
            seg_diff +
            diversity_penalty
        )

        if score < best_score:
            best_score = score
            best_a_speakers = a["speaker_id"]
            best_b_speakers = b["speaker_id"]

    # Filter original df by best speakers (no speaker overlap guaranteed)
    a_df = df[df["speaker_id"].isin(best_a_speakers)].reset_index(drop=True)
    b_df = df[df["speaker_id"].isin(best_b_speakers)].reset_index(drop=True)

    # Save metadata CSVs
    os.makedirs(output_dir, exist_ok=True)
    a_df.to_csv(f"{output_dir}/{split_name}_real_A.csv", index=False)
    b_df.to_csv(f"{output_dir}/{split_name}_real_B.csv", index=False)

    # Verify
    overlap = set(a_df["speaker_id"]) & set(b_df["speaker_id"])
    print(f"{split_name}: A={len(a_df)}, B={len(b_df)}, diff={abs(len(a_df)-len(b_df))}, overlap={len(overlap)}")

    return a_df, b_df
