# -*- coding: utf-8 -*-
"""voice_conversion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ku8HwrMJ_n5LAyKg0sqJ0eZcpOd_LKnm
"""

import os
import numpy as np
import pyworld as pw
import librosa
import soundfile as sf
import sw  # spectral warping library

# =====================================================
# Adult → Child
# =====================================================
EPSILON = 1e-8
F0_MAX = 600
F0_MIN = 50
GENDER_F0_THRESHOLD = 160

def process_adult_to_child(sig, fs,
            target_f0=None,
            warping_function='linear',
            warping_factor=1,
            vowel_stretch_factor=1):

    original_len = len(sig)
    _f0_h, t_h = pw.harvest(sig, fs)
    f0_h = pw.stonemask(sig, _f0_h, t_h, fs)
    sp_h = pw.cheaptrick(sig, f0_h, t_h, fs)
    ap_h = pw.d4c(sig, f0_h, t_h, fs)
    f0_mean = np.mean(f0_h[f0_h > F0_MIN])

    if target_f0 is None:
        target_f0 = f0_mean

    f0_shift = target_f0 - f0_mean
    f0_out = f0_h
    f0_out[f0_h > F0_MIN] = f0_h[f0_h > F0_MIN] + f0_shift
    f0_out[f0_out > F0_MAX] = F0_MAX

    sp_out = sw.transform(sp_h, warping_factor, fs, warping_function)
    harmonics = f0_h != 0
    change_points = np.nonzero(harmonics != np.roll(harmonics, 1))[0] + 1
    if len(change_points) > 1 and change_points[-1] >= len(harmonics):
        change_points = change_points[:-1]
    is_vowel = harmonics[np.insert(change_points, 0, 0)]

    sp_out_segs = np.split(sp_out, change_points)
    ap_segs = np.split(ap_h, change_points)
    f0_out_segs = np.split(f0_out, change_points)
    y_segs = []

    for i in range(len(sp_out_segs)):
        y_seg = pw.synthesize(
            f0_out_segs[i],
            sp_out_segs[i],
            ap_segs[i],
            fs,
            vowel_stretch_factor * 4 if is_vowel[i] else 5
        )
        y_segs.append(y_seg)

    y_h = np.concatenate(y_segs)
    if len(y_h) > original_len:
        y_h = y_h[:original_len]
    elif len(y_h) < original_len:
        y_h = np.pad(y_h, (0, original_len - len(y_h)))

    return y_h

def randomize_parameters_adult_to_child(sig, fs,
                         target_f0=None,
                         warping_function=None,
                         warping_factor=None,
                         vowel_stretch_factor=None):

    params = {}
    if target_f0 is None:
        params['target_f0'] = np.random.uniform(240, 300)
    else:
        params['target_f0'] = float(target_f0)
    if vowel_stretch_factor is None:
        params['vowel_stretch_factor'] = np.random.uniform(1.1, 1.4)
    else:
        params['vowel_stretch_factor'] = float(vowel_stretch_factor)
    if warping_function is None:
        _f0_h, t_h = pw.harvest(sig, fs)
        f0_h = pw.stonemask(sig, _f0_h, t_h, fs)
        f0_mean = np.mean(f0_h[f0_h > 50])
        if f0_mean < GENDER_F0_THRESHOLD:
            params['warping_function'] = 'linear'
            if warping_factor is None:
                params['warping_factor'] = np.random.uniform(1.2, 1.4)
            else:
                params['warping_factor'] = float(warping_factor)
        else:
            params['warping_function'] = 'piecewise'
            if warping_factor is None:
                params['warping_factor'] = np.random.uniform(1.1, 1.25)
            else:
                params['warping_factor'] = float(warping_factor)
    return params

def convert_adult_to_child_dataset(input_folder, output_folder):
    os.makedirs(output_folder, exist_ok=True)
    for file in os.listdir(input_folder):
        if not file.lower().endswith((".wav", ".mp3")):
            continue
        input_path = os.path.join(input_folder, file)
        sig, fs = librosa.load(input_path, sr=None)
        params = randomize_parameters_adult_to_child(sig, fs)
        y = process_adult_to_child(sig, fs,
                                   target_f0=params['target_f0'],
                                   warping_function=params['warping_function'],
                                   warping_factor=params['warping_factor'],
                                   vowel_stretch_factor=params['vowel_stretch_factor'])
        name = os.path.splitext(file)[0]
        out_path = os.path.join(output_folder, name + "_vc.wav")
        sf.write(out_path, y, fs)
        print("Adult → Child conversion complete.")


# =====================================================
# Child → Adult
# =====================================================
EPSILON = 1e-8
F0_MAX = 600
F0_MIN = 50
GENDER_F0_THRESHOLD = 180

def process_child_to_adult(sig, fs,
            target_f0=None,
            warping_function='linear',
            warping_factor=1,
            vowel_stretch_factor=1):

    original_len = len(sig)
    _f0_h, t_h = pw.harvest(sig, fs)
    f0_h = pw.stonemask(sig, _f0_h, t_h, fs)
    sp_h = pw.cheaptrick(sig, f0_h, t_h, fs)
    ap_h = pw.d4c(sig, f0_h, t_h, fs)
    f0_mean = np.mean(f0_h[f0_h > F0_MIN])
    if target_f0 is None:
        target_f0 = f0_mean
    f0_shift = target_f0 - f0_mean
    f0_out = f0_h
    f0_out[f0_h > F0_MIN] = f0_h[f0_h > F0_MIN] + f0_shift
    f0_out[f0_out > F0_MAX] = F0_MAX
    sp_out = sw.transform(sp_h, warping_factor, fs, warping_function)
    harmonics = f0_h != 0
    change_points = np.nonzero(harmonics != np.roll(harmonics, 1))[0] + 1
    if len(change_points) > 1 and change_points[-1] >= len(harmonics):
        change_points = change_points[:-1]
    is_vowel = harmonics[np.insert(change_points, 0, 0)]
    sp_out_segs = np.split(sp_out, change_points)
    ap_segs = np.split(ap_h, change_points)
    f0_out_segs = np.split(f0_out, change_points)
    y_segs = []
    for i in range(len(sp_out_segs)):
        y_seg = pw.synthesize(
            f0_out_segs[i],
            sp_out_segs[i],
            ap_segs[i],
            fs,
            vowel_stretch_factor * 4 if is_vowel[i] else 5
        )
        y_segs.append(y_seg)
    y_h = np.concatenate(y_segs)
    if len(y_h) > original_len:
        y_h = y_h[:original_len]
    elif len(y_h) < original_len:
        y_h = np.pad(y_h, (0, original_len - len(y_h)))
    return y_h

def randomize_parameters_child_to_adult(sig, fs,
                         target_f0=None,
                         warping_function=None,
                         warping_factor=None,
                         vowel_stretch_factor=None):

    params = {}
    _f0_h, t_h = pw.harvest(sig, fs)
    f0_h = pw.stonemask(sig, _f0_h, t_h, fs)
    f0_mean = np.mean(f0_h[f0_h > F0_MIN])
    if f0_mean > GENDER_F0_THRESHOLD:
        gender = 'female_child'
    else:
        gender = 'male_child'
    if target_f0 is None:
        if gender == 'male_child':
            params['target_f0'] = np.random.uniform(100, 120)
        else:
            params['target_f0'] = np.random.uniform(175, 210)
    else:
        params['target_f0'] = float(target_f0)
    if vowel_stretch_factor is None:
        params['vowel_stretch_factor'] = np.random.uniform(1.0, 1.1)
    else:
        params['vowel_stretch_factor'] = float(vowel_stretch_factor)
    if warping_function is None:
        if gender in ['male_child', 'female_child']:
            params['warping_function'] = 'linear'
            if warping_factor is None:
                if gender == 'male_child':
                    params['warping_factor'] = np.random.uniform(0.65, 0.75)
                else:
                    params['warping_factor'] = np.random.uniform(0.75, 0.85)
            else:
                params['warping_factor'] = float(warping_factor)
        else:
            params['warping_function'] = 'piecewise'
            if warping_factor is None:
                params['warping_factor'] = np.random.uniform(1.1, 1.25)
            else:
                params['warping_factor'] = float(warping_factor)
    return params

def convert_child_to_adult_dataset(input_folder, output_folder):
    os.makedirs(output_folder, exist_ok=True)
    for file in os.listdir(input_folder):
        if not file.lower().endswith((".wav", ".mp3")):
            continue
        input_path = os.path.join(input_folder, file)
        sig, fs = librosa.load(input_path, sr=None)
        params = randomize_parameters_child_to_adult(sig, fs)
        y = process_child_to_adult(sig, fs,
                                   target_f0=params['target_f0'],
                                   warping_function=params['warping_function'],
                                   warping_factor=params['warping_factor'],
                                   vowel_stretch_factor=params['vowel_stretch_factor'])
        name = os.path.splitext(file)[0]
        out_path = os.path.join(output_folder, name + "_vc.wav")
        sf.write(out_path, y, fs)
        print("Child → Adult conversion complete.")