# -*- coding: utf-8 -*-
"""chatterbox_tts_ubdated.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_zkWaF4QBXaDlVx6MZ-9qKY1huKFADYa
"""

# -*- coding: utf-8 -*-
"""
Chatterbox TTS - Voice Cloning
Notebook-matched settings for natural target-like speech
"""

import os
import torch
import torchaudio
import numpy as np

# ─────────────────────────────────────────
# MODEL LOADER (singleton)
# ─────────────────────────────────────────
_MODEL = None

def get_model():
    global _MODEL

    if _MODEL is None:
        from chatterbox.tts import ChatterboxTTS

        device = "cuda" if torch.cuda.is_available() else "cpu"
        print(f"Loading model on device: {device}")

        try:
            _MODEL = ChatterboxTTS.from_pretrained(device=device)
            print("✅ Model loaded successfully")

        except Exception:
            print("Trying CPU fallback...")
            _MODEL = ChatterboxTTS.from_pretrained(device="cpu")
            print("✅ Model loaded on CPU")

    return _MODEL


# ─────────────────────────────────────────
# TEXT CHUNKER (same notebook logic)
# ─────────────────────────────────────────
def split_into_chunks(text: str, max_words: int = 50) -> list[str]:

    sentences = text.strip().replace("\n", " ").split(".")
    sentences = [s.strip() for s in sentences if s.strip()]

    chunks = []
    current_chunk = ""
    current_word_count = 0

    for sentence in sentences:

        sentence_words = sentence.split()

        if current_word_count + len(sentence_words) > max_words and current_chunk:

            chunks.append(current_chunk.strip() + ".")
            current_chunk = sentence
            current_word_count = len(sentence_words)

        else:

            if current_chunk:
                current_chunk += ". " + sentence
            else:
                current_chunk = sentence

            current_word_count += len(sentence_words)

    if current_chunk:
        chunks.append(current_chunk.strip() + ".")

    return chunks


# ─────────────────────────────────────────
# MAIN FUNCTION
# ─────────────────────────────────────────
def run_chatterbox_tts(
    text: str,
    reference_audio_path: str,
    output_path: str = "output.wav",
    exaggeration: float = 0.5,
    cfg_weight: float = 0.5,
    max_chunk_words: int = 50,
) -> np.ndarray:
    """
    Generate speech using notebook-matched settings.

    Args:
        text                : input text
        reference_audio_path: reference audio path
        output_path         : unused (kept for compatibility)
        exaggeration        : expression intensity
        cfg_weight          : similarity to reference voice
        max_chunk_words     : max words per chunk

    Returns:
        np.ndarray waveform
    """

    # ── Reference audio validation ──────────────────
    if not os.path.exists(reference_audio_path):
        raise FileNotFoundError(
            f"Reference audio not found: {reference_audio_path}"
        )

    wav_check, sr_check = torchaudio.load(reference_audio_path)

    duration = wav_check.shape[1] / sr_check

    print(
        f"Reference audio: "
        f"{duration:.1f}s | {sr_check}Hz | {wav_check.shape[0]}ch"
    )

    # ── Load model ─────────────────────────
    model = get_model()

    # ── Split text into chunks ─────────────────────────
    chunks = split_into_chunks(text, max_chunk_words)

    # ── Generation ──────────────────────────────
    wav_tensors = []

    for i, chunk in enumerate(chunks):

        print(f"[{i+1}/{len(chunks)}] {chunk[:60]}...")

        try:

            wav = model.generate(
                text=chunk,
                audio_prompt_path=reference_audio_path,
                exaggeration=exaggeration,
                cfg_weight=cfg_weight,
            )

            wav_tensors.append(wav)

        except Exception as e:

            print(f"Chunk {i+1} failed: {e}")
            continue

        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    if not wav_tensors:
        raise RuntimeError("No audio generated")

    # ── Merge and convert to waveform ─────────────────────────────
    full_audio = torch.cat(wav_tensors, dim=1)

    audio_np = (
        full_audio
        .squeeze()
        .detach()
        .cpu()
        .numpy()
        .astype(np.float32)
    )

    print("Success!")

    return audio_np
