# -*- coding: utf-8 -*-
"""chatterbox_tts_ubdated.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_zkWaF4QBXaDlVx6MZ-9qKY1huKFADYa
"""

# -*- coding: utf-8 -*-
"""
Chatterbox TTS - Voice Cloning
إعدادات مطابقة للنوتبوك اللي يعطي صوت طبيعي مثل التارقت
"""

import os
import torch
import torchaudio
import numpy as np

# ─────────────────────────────────────────
# MODEL LOADER (singleton)
# ─────────────────────────────────────────
_MODEL = None

def get_model():
    global _MODEL
    if _MODEL is None:
        from chatterbox.tts import ChatterboxTTS
        device = "cuda" if torch.cuda.is_available() else "cpu"
        print(f"Loading model on device: {device}")
        try:
            _MODEL = ChatterboxTTS.from_pretrained(device=device)
            print("✅ Model loaded successfully")
        except Exception:
            print("Trying CPU fallback...")
            _MODEL = ChatterboxTTS.from_pretrained(device="cpu")
            print("✅ Model loaded on CPU")
    return _MODEL


# ─────────────────────────────────────────
# TEXT CHUNKER  (نفس منطق النوتبوك بالضبط)
# ─────────────────────────────────────────
def split_into_chunks(text: str, max_words: int = 50) -> list[str]:
    sentences = text.strip().replace("\n", " ").split(".")
    sentences = [s.strip() for s in sentences if s.strip()]

    chunks = []
    current_chunk = ""
    current_word_count = 0

    for sentence in sentences:
        sentence_words = sentence.split()
        if current_word_count + len(sentence_words) > max_words and current_chunk:
            chunks.append(current_chunk.strip() + ".")
            current_chunk = sentence
            current_word_count = len(sentence_words)
        else:
            if current_chunk:
                current_chunk += ". " + sentence
            else:
                current_chunk = sentence
            current_word_count += len(sentence_words)

    if current_chunk:
        chunks.append(current_chunk.strip() + ".")

    return chunks


# ─────────────────────────────────────────
# MAIN FUNCTION
# ─────────────────────────────────────────
def run_chatterbox_tts(
    text: str,
    reference_audio_path: str,
    output_path: str = "output.wav",
    exaggeration: float = 0.6,   # نفس النوتبوك
    cfg_weight: float = 0.4,     # نفس النوتبوك
    max_chunk_words: int = 50,   # نفس النوتبوك
) -> str:
    """
    يولّد صوت بنفس إعدادات النوتبوك.

    Args:
        text               : النص المراد تحويله
        reference_audio_path: مسار ملف الصوت المرجعي (WAV, >= 6 ثواني, mono أفضل)
        output_path        : مسار حفظ الناتج
        exaggeration       : مدى المبالغة في التعبير  (0.3 هادئ ← 1.0 درامي)
        cfg_weight         : قرب الصوت من المرجع      (0.3 حر ← 0.7 ملتزم)
        max_chunk_words    : الحد الأقصى للكلمات في كل chunk

    Returns:
        مسار ملف الصوت الناتج
    """

    # ── التحقق من ملف المرجع ──────────────────
    if not os.path.exists(reference_audio_path):
        raise FileNotFoundError(f"❌ ملف الصوت المرجعي غير موجود: {reference_audio_path}")

    wav_check, sr_check = torchaudio.load(reference_audio_path)
    duration = wav_check.shape[1] / sr_check
    print(f"🎤 Reference audio: {duration:.1f}s  |  {sr_check}Hz  |  {wav_check.shape[0]}ch")
    if duration < 6:
        print("⚠️  تحذير: الصوت المرجعي أقل من 6 ثواني، قد يضعف جودة الاستنساخ")

    # ── تحميل المودل ─────────────────────────
    model = get_model()

    # ── تقطيع النص ───────────────────────────
    chunks = split_into_chunks(text, max_chunk_words)
    print(f"📝 النص: {len(text.split())} كلمة  |  {len(chunks)} chunk")
    print(f"🎛️  exaggeration={exaggeration}  cfg_weight={cfg_weight}")

    # ── التوليد ──────────────────────────────
    wav_tensors = []
    for i, chunk in enumerate(chunks):
        print(f"  [{i+1}/{len(chunks)}] {chunk[:60]}...")
        try:
            wav = model.generate(
                text=chunk,
                audio_prompt_path=reference_audio_path,   # ← الصوت المرجعي
                exaggeration=exaggeration,
                cfg_weight=cfg_weight,
            )
            wav_tensors.append(wav)
        except Exception as e:
            print(f"  ❌ خطأ في chunk {i+1}: {e}")
            continue

        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    if not wav_tensors:
        raise RuntimeError("❌ لم يُولَّد أي صوت")

    # ── دمج وحفظ ─────────────────────────────
    full_audio = torch.cat(wav_tensors, dim=1)
    torchaudio.save(output_path, full_audio, model.sr)
    print(f"✅ تم الحفظ: {output_path}")
    return output_path