# -*- coding: utf-8 -*-
"""knn_vc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rsQ8MHx4MI8i8K-C36Ewbn1JuLr8_PqO
"""

import torch
import uuid
import soundfile as sf

_MODEL = None


def get_model():
    global _MODEL
    if _MODEL is None:
        from hubconf import knn_vc
        _MODEL = knn_vc(
            pretrained=True,
            prematched=True,
            device='cuda' if torch.cuda.is_available() else 'cpu'
        )
    return _MODEL


def run_knn(src_audio, tgt_audio, sr=16000):

    model = get_model()

    src_path = f"/content/{uuid.uuid4()}_src.wav"
    tgt_path = f"/content/{uuid.uuid4()}_tgt.wav"
    out_path = f"/content/{uuid.uuid4()}_out.wav"

    sf.write(src_path, src_audio, sr)
    sf.write(tgt_path, tgt_audio, sr)

    q = model.get_features(src_path)
    m = model.get_matching_set([tgt_path])

    out = model.match(q, m, topk=4)

    sf.write(out_path, out.cpu().numpy(), sr)

    return out_path