# -*- coding: utf-8 -*-
"""knnvc_conversion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RNBMxkbG4xjXylFcKmYkeovr8GKcc6hS
"""

# =====================================================
# Voice Conversion Module - kNN-VC
# =====================================================
#
# This module converts source voices to target voices
# using the kNN-VC model.
#
# Requirements (in Google Drive):
#   1. Source folder  (e.g. children voices)
#   2. Target folder  (e.g. adult voices)
#
# Output is saved automatically to:
#   /content/drive/MyDrive/output_cloning_knn/
#
# Usage from main:
#   from knnvc_conversion import load_knnvc_model, run_knnvc_random
#
#   model = load_knnvc_model()
#   run_knnvc_random(model, source_folder, target_folder, n_samples=5)
#
# =====================================================

import os
import sys
import random
import torch
import librosa
import soundfile as sf
import numpy as np


# =====================================================
# Load Model
# =====================================================

def load_knnvc_model():
    import subprocess
    subprocess.run(['git', 'clone', 'https://github.com/bshall/knn-vc.git'],
                   capture_output=True)

    if '/content/knn-vc' not in sys.path:
        sys.path.insert(0, '/content/knn-vc')

    from hubconf import knn_vc
    device = 'cuda' if torch.cuda.is_available() else 'cpu'

    model = knn_vc(
        pretrained = True,
        progress   = True,
        prematched = True,
        device     = device
    )

    print(f"kNN-VC loaded on {device}")
    return model


# =====================================================
# Convert Single File
# =====================================================

def run_knnvc(model, source_path, target_path, topk=4, sr=16000):
    """
    source_path : path to source audio
    target_path : path to target (reference) audio
    topk        : number of nearest neighbors
    sr          : sample rate

    returns:
        out_wav : converted audio tensor
        info    : dict with conversion details
    """

    y_source, _ = librosa.load(source_path, sr=sr)
    y_target, _ = librosa.load(target_path, sr=sr)

    src_16k = '/content/source_16k.wav'
    tgt_16k = '/content/target_16k.wav'

    sf.write(src_16k, y_source, sr)
    sf.write(tgt_16k, y_target, sr)

    query_seq    = model.get_features(src_16k)
    matching_set = model.get_matching_set([tgt_16k])

    out_wav = model.match(query_seq, matching_set, topk=topk)

    info = {
        "model":    "knn-vc",
        "source":   source_path,
        "target":   target_path,
        "topk":     topk,
        "sr":       sr,
        "duration": len(out_wav) / sr
    }

    print(f"converted | duration: {info['duration']:.2f}s | topk: {topk}")
    return out_wav, info


# =====================================================
# Convert N Random Pairs from Two Folders
# =====================================================

def run_knnvc_random(model, source_folder, target_folder, n_samples=1, topk=4, sr=16000):
    """
    source_folder : folder containing source audio files
    target_folder : folder containing target (reference) audio files
    n_samples     : number of conversions to perform
    topk          : number of nearest neighbors
    sr            : sample rate

    - for each sample, picks a random source and target
    - ensures source filename != target filename
    - saves all results to output_cloning_knn/

    returns:
        all_info : list of dicts with conversion details
    """

    valid_ext = (".wav", ".mp3")

    source_files = [f for f in os.listdir(source_folder) if f.endswith(valid_ext)]
    target_files = [f for f in os.listdir(target_folder) if f.endswith(valid_ext)]

    if not source_files:
        raise ValueError(f"Source folder is empty: {source_folder}")
    if not target_files:
        raise ValueError(f"Target folder is empty: {target_folder}")

    output_folder = "/content/drive/MyDrive/output_cloning_knn"
    os.makedirs(output_folder, exist_ok=True)

    all_info = []

    for i in range(n_samples):

        print(f"\n--- sample {i+1}/{n_samples} ---")

        # pick random source
        source_file = random.choice(source_files)

        # pick random target, ensuring it differs from source
        target_candidates = [f for f in target_files if f != source_file]
        if not target_candidates:
            raise ValueError("No valid target found that differs from source")
        target_file = random.choice(target_candidates)

        source_path = os.path.join(source_folder, source_file)
        target_path = os.path.join(target_folder, target_file)

        print(f"source : {source_file}")
        print(f"target : {target_file}")

        # run conversion
        out_wav, info = run_knnvc(model, source_path, target_path, topk, sr)

        # save output
        out_name    = f"{os.path.splitext(source_file)[0]}_knnvc_{i:03d}.wav"
        output_path = os.path.join(output_folder, out_name)
        sf.write(output_path, out_wav.cpu().numpy(), sr)

        info["source_file"] = source_file
        info["target_file"] = target_file
        info["sample_id"]   = i
        info["output_path"] = output_path

        print(f"saved -> {output_path}")
        all_info.append(info)

    print(f"\ndone | total conversions: {len(all_info)}")
    return all_info


# =====================================================
# Engine Registry
# =====================================================

VC_ENGINES = {
    "knn-vc": run_knnvc
}