# -*- coding: utf-8 -*-
"""koko_vc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18FvBA6G82SZZJWY-MQa8lEjmwXGNtUv8
"""

import uuid
import soundfile as sf
import librosa
import numpy as np

_MODEL = None


def get_model():
    global _MODEL
    if _MODEL is None:
        from core.cloner import KokoClone
        _MODEL = KokoClone()
    return _MODEL


def run_koko(src_audio, tgt_audio, sr=16000):

    model = get_model()

    src_path = f"/content/{uuid.uuid4()}_src.wav"
    tgt_path = f"/content/{uuid.uuid4()}_tgt.wav"
    out_path = f"/content/{uuid.uuid4()}_out.wav"

    sf.write(src_path, src_audio, sr)
    sf.write(tgt_path, tgt_audio, sr)

    model.convert(
        source_audio=src_path,
        reference_audio=tgt_path,
        output_path=out_path
    )

    audio, _ = librosa.load(out_path, sr=sr)

    return audio.astype(np.float32)
