# -*- coding: utf-8 -*-
"""noise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZPKdp2cSjVWmZ0Pjx1OlSVrQQFHaxbvm
"""

# =====================================================
# Noise Augmentation Module
# =====================================================



# =====================================================
# Noise Augmentation Module
# =====================================================
#
# عشان يشتغل هذا الكود تحتاج ترفع في Google Drive:
#
#   1. noise-free-sound-0001.wav  ← أصوات كافيه / ناس
#   2. computernoise.mp3          ← أصوات كمبيوتر / بيئة
#   3. sample-000042.mp3          ← الصوت اللي تبي تطبق عليه النويز
#
# ── لو تبي تشغله على ملف واحد ───────────────────────
#
#   استخدم: run_noise_on_file()
#   وحدد: VOICE_PATH = "مسار الملف"
#
# ── لو عندك مجلد فيه أصوات ──────────────────────────
#
#   بدّل في آخر الكود:
#
#     VOICE_PATH  →  INPUT_FOLDER  = "مسار المجلد"
#                    OUTPUT_FOLDER = "مسار مجلد النتائج"
#
#   وبدّل دالة التشغيل:
#
#     run_noise_on_file()  →  run_noise_on_folder()
#
# =====================================================

# Cell 1: Install & Imports
import subprocess, sys
subprocess.run([sys.executable, '-m', 'pip', 'install', 'torchaudio', '-q'])

import os
import torch
import torchaudio
import numpy as np
import soundfile as sf
import IPython.display as ipd
from google.colab import drive

# Cell 2: Mount Drive
drive.mount('/content/drive')


def apply_noise(waveform, seed, config):
    snr_db_min = float(config.get('snr_db_min', 5))
    snr_db_max = float(config.get('snr_db_max', 20))
    g = torch.Generator(device=waveform.device).manual_seed(int(seed))
    snr_db = torch.empty((), device=waveform.device).uniform_(snr_db_min, snr_db_max, generator=g).item()
    sig_power = waveform.pow(2).mean()
    noise_power = sig_power / (10 ** (snr_db / 10))
    noise_std = noise_power.sqrt()
    noise = torch.randn(waveform.numel(), device=waveform.device, generator=g).view_as(waveform) * noise_std
    return (waveform + noise).clamp_(-1, 1)

def apply_background_mix(waveform, background, seed, config):
    snr_db_min = float(config.get('snr_db_min', 0))
    snr_db_max = float(config.get('snr_db_max', 15))
    clamp_min  = float(config.get('clamp_min', -1))
    clamp_max  = float(config.get('clamp_max',  1))
    background = background.to(device=waveform.device, dtype=waveform.dtype)
    g = torch.Generator(device=waveform.device).manual_seed(int(seed))
    snr_db = torch.empty((), device=waveform.device).uniform_(snr_db_min, snr_db_max, generator=g).item()
    def to_ct(x): return x.unsqueeze(0) if x.ndim == 1 else x
    x = to_ct(waveform); n = to_ct(background)
    C, T = x.shape; Cn, Tn = n.shape
    if Cn == 1 and C > 1:   n = n.expand(C, -1)
    elif Cn != C:            raise ValueError(f'Channel mismatch')
    if Tn < T:
        n = n.repeat(1, (T + Tn - 1) // Tn)[:, :T]
    elif Tn > T:
        start = int(torch.randint(0, Tn - T + 1, (1,), generator=g, device=waveform.device).item())
        n = n[:, start:start + T]
    sig_power   = x.pow(2).mean()
    noise_power = n.pow(2).mean().clamp_min(1e-12)
    scale = (sig_power / (10 ** (snr_db / 10)) / noise_power).sqrt()
    y = x + n * scale
    if waveform.ndim == 1: y = y.squeeze(0)
    return y.clamp_(clamp_min, clamp_max)

# =====================================================
# Noise Augmentation Module
# =====================================================

DEFAULT_SR = 16000

NOISE_TYPES = ["gaussian", "cafe", "environmental"]

NOISE_LEVELS = {
    "clean": None,
    "low":   20,
    "med":   10,
    "hard":  5
}

NOISE_PROBS = {
    "clean": 0.50,
    "low":   0.25,
    "med":   0.20,
    "hard":  0.05
}

def load_audio(path, target_sr=DEFAULT_SR):
    wav, sr = torchaudio.load(path)
    if sr != target_sr:
        wav = torchaudio.functional.resample(wav, sr, target_sr)
    if wav.shape[0] > 1:
        wav = wav.mean(0, keepdim=True)
    wav = wav / wav.abs().max().clamp_min(1e-9)
    return wav.squeeze(0), target_sr

def load_noise_files(cafe_path, environmental_path, sr=DEFAULT_SR):
    cafe_wav, _          = load_audio(cafe_path,          target_sr=sr)
    environmental_wav, _ = load_audio(environmental_path, target_sr=sr)
    print(f" cafe loaded:          {cafe_wav.shape[0]/sr:.2f}s")
    print(f" environmental loaded: {environmental_wav.shape[0]/sr:.2f}s")
    return {
        "cafe":          cafe_wav,
        "environmental": environmental_wav
    }

def pick_noise_level():
    levels = list(NOISE_PROBS.keys())
    probs  = list(NOISE_PROBS.values())
    return np.random.choice(levels, p=probs)

def pick_noise_type():
    idx = np.random.randint(0, len(NOISE_TYPES))
    return NOISE_TYPES[idx]

def apply_noise_to_segment(segment, noise_buffers, seed=None):
    if seed is None:
        seed = int(np.random.randint(0, 99999))

    level = pick_noise_level()

    if level == "clean":
        info = {"level": "clean", "noise_type": None, "snr_db": None, "seed": seed}
        return segment, info

    noise_type = pick_noise_type()
    snr_db     = NOISE_LEVELS[level]
    config     = {"snr_db_min": snr_db, "snr_db_max": snr_db}

    if noise_type == "gaussian":
        noisy = apply_noise(segment, seed, config)
    else:
        noisy = apply_background_mix(segment, noise_buffers[noise_type], seed, config)

    info = {"level": level, "noise_type": noise_type, "snr_db": snr_db, "seed": seed}
    return noisy, info

def run_noise_on_segments(segments, noise_buffers):
    results = []
    for i, segment in enumerate(segments):
        seed = int(np.random.randint(0, 99999))
        noisy_segment, info = apply_noise_to_segment(segment, noise_buffers, seed=seed)
        results.append({
            "segment_id":    i,
            "noisy_segment": noisy_segment,
            "noise_info":    info
        })
        print(f"Segment {i:03d} | level: {info['level']:5s} | "
              f"type: {str(info['noise_type']):15s} | SNR: {info['snr_db']}")
    return results

# ── Run on Single File ────────────────────────────────
def run_noise_on_file(file_path, noise_buffers, segment_sec=2, sr=DEFAULT_SR):
    audio, sr = load_audio(file_path, target_sr=sr)
    seg_len   = segment_sec * sr
    segments  = [audio[i:i+seg_len] for i in range(0, len(audio), seg_len)]
    segments  = [s for s in segments if len(s) == seg_len]
    print(f" {file_path}")
    print(f"   Duration: {len(audio)/sr:.2f}s | Segments: {len(segments)} x {segment_sec}s\n")
    return run_noise_on_segments(segments, noise_buffers)

# ── Run on Folder ─────────────────────────────────────
def run_noise_on_folder(input_folder, output_folder, noise_buffers, segment_sec=2, sr=DEFAULT_SR):
    os.makedirs(output_folder, exist_ok=True)
    all_results = {}
    for file in os.listdir(input_folder):
        if file.endswith(".wav") or file.endswith(".mp3"):
            input_path = os.path.join(input_folder, file)
            results    = run_noise_on_file(input_path, noise_buffers, segment_sec, sr)
            for r in results:
                out_name = f"{os.path.splitext(file)[0]}_seg{r['segment_id']:03d}.wav"
                out_path = os.path.join(output_folder, out_name)
                sf.write(out_path, r['noisy_segment'].numpy(), sr)
            all_results[file] = results
    return all_results

NOISE_ENGINES = {
    "gaussian":      lambda seg, buf, seed: apply_noise(
                         seg, seed, {"snr_db_min": 5, "snr_db_max": 20}),
    "cafe":          lambda seg, buf, seed: apply_background_mix(
                         seg, buf["cafe"],          seed, {"snr_db_min": 5, "snr_db_max": 20}),
    "environmental": lambda seg, buf, seed: apply_background_mix(
                         seg, buf["environmental"], seed, {"snr_db_min": 5, "snr_db_max": 20}),
}

VOICE_PATH         = "/content/drive/MyDrive/sample-000042.mp3"
CAFE_PATH          = "/content/drive/MyDrive/noise-free-sound-0001.wav"
ENVIRONMENTAL_PATH = "/content/drive/MyDrive/computernoise.mp3"

noise_buffers = load_noise_files(CAFE_PATH, ENVIRONMENTAL_PATH)
results       = run_noise_on_file(VOICE_PATH, noise_buffers, segment_sec=2)

for r in results[:3]:
    print(f"\nSegment {r['segment_id']} | {r['noise_info']}")
    display(ipd.Audio(r['noisy_segment'].numpy(), rate=DEFAULT_SR))