# -*- coding: utf-8 -*-
"""replay_attack_v.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NKKRrZRhAJudWLoUiVlj1lTk69Zn8Oy8
"""

import numpy as np
import librosa
import soundfile as sf
import scipy.signal as signal
import matplotlib.pyplot as plt
from pydub import AudioSegment
from google.colab import files
from IPython.display import Audio, display
import os

# =====================================================
# Replay Attack Module
# =====================================================

# -----------------------------------------------------
# Simulate speaker filter
# Limits the frequency range that a typical speaker can produce
# -----------------------------------------------------
def speaker_filter(audio, sr):
    b, a = signal.butter(4, [300/(sr/2), 4000/(sr/2)], btype='band')
    return signal.lfilter(b, a, audio)


# -----------------------------------------------------
# Generate Room Impulse Response (RIR)
# Simulates sound reflections in a room
# -----------------------------------------------------
def generate_rir(sr, duration=0.15):

    # Time axis for the RIR
    t = np.linspace(0, duration, int(sr * duration))

    # Direct sound from the speaker
    direct = np.zeros(len(t))
    direct[0] = 1.0

    # Reflections from walls
    reflections = 0.3 * np.exp(-12 * t) * np.random.normal(1, 0.05, len(t))

    # Combine direct sound with reflections
    rir = direct + reflections

    # Normalize RIR
    rir /= np.max(np.abs(rir))

    return rir


# -----------------------------------------------------
# Simulate microphone filter
# Most microphones cut off high frequencies
# -----------------------------------------------------
def mic_filter(audio, sr):
    b, a = signal.butter(4, 6000/(sr/2), btype='low')
    return signal.lfilter(b, a, audio)


# -----------------------------------------------------
# Add environmental noise
# Simulates real-world recording conditions
# -----------------------------------------------------
def add_noise(audio, snr_db=15):

    noise = np.random.normal(0, 1, len(audio))

    audio_power = np.mean(audio**2)
    noise_power = np.mean(noise**2)

    factor = np.sqrt(audio_power / (10**(snr_db/10) * noise_power))

    noise = noise * factor

    return audio + noise


# -----------------------------------------------------
# Main function to generate Replay Attack audio
# -----------------------------------------------------
def create_replay_attack(audio, sr):

    # 1. Simulate speaker playback
    audio_spk = speaker_filter(audio, sr)

    # 2. Generate room characteristics
    rir = generate_rir(sr)

    # 3. Apply room effect
    audio_room = signal.convolve(audio_spk, rir, mode='same')

    # 4. Simulate microphone capture
    audio_mic = mic_filter(audio_room, sr)

    # 5. Add environmental noise
    audio_replay = add_noise(audio_mic, snr_db=35)

    # 6. Normalize the audio
    audio_replay = audio_replay / np.max(np.abs(audio_replay))

    return audio_replay


# =====================================================
# Apply Replay Attack to Dataset (Folder)
# =====================================================
def convert_replay_attack_dataset(input_folder, output_folder):

    os.makedirs(output_folder, exist_ok=True)

    for file in os.listdir(input_folder):

        if not file.lower().endswith((".wav", ".mp3")):
            continue

        input_path = os.path.join(input_folder, file)

        # ---- Read audio ----
        audio, sr = sf.read(input_path)

        # ---- Apply replay attack ----
        replay_audio = create_replay_attack(audio, sr)

        # ---- Save output ----
        name = os.path.splitext(file)[0]
        out_path = os.path.join(output_folder, name + "_ra.wav")

        sf.write(out_path, replay_audio, sr)

        print("Replay attack applied:", file)