# -*- coding: utf-8 -*-
"""seed_vc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19facvZytQpQtwhMvRdVylI3PSVT0nNB4
"""

# -*- coding: utf-8 -*-

import os
import uuid
import subprocess
import soundfile as sf
import glob

# 🔥 المسار الصحيح للمشروع (مهم جدًا)
SEED_DIR = "/content/Robust-Multimodal-Age-Verification-for-Online-Gaming-Chat/seed-vc"

# مجلد الإخراج داخل نفس المشروع
OUTPUT_DIR = os.path.join(SEED_DIR, "output_results")


def run_seed(src_audio, tgt_audio, sr=16000):

    # 1. تجهيز الملفات
    u_id = str(uuid.uuid4())[:8]
    src_path = f"/content/s_{u_id}.wav"
    tgt_path = f"/content/t_{u_id}.wav"

    os.makedirs(OUTPUT_DIR, exist_ok=True)

    sf.write(src_path, src_audio, sr)
    sf.write(tgt_path, tgt_audio, sr)

    print("--- Launching Seed-VC Engine ---")

    # 2. أمر التشغيل
    cmd = [
        "python",
        "inference_v2.py",
        "--source", src_path,
        "--target", tgt_path,
        "--output", OUTPUT_DIR,
        "--diffusion-steps", "50",
        "--similarity-cfg-rate", "0.75",
        "--convert-style", "True"   # 🔥 مهم: True كـ string صحيحة
    ]

    # 3. تشغيل مع عرض مباشر (أفضل debug)
    process = subprocess.Popen(
        cmd,
        cwd=SEED_DIR,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1
    )

    for line in process.stdout:
        print(line, end='')

    process.wait()

    if process.returncode != 0:
        raise RuntimeError(f"❌ Seed-VC execution failed with code {process.returncode}")

    # 4. البحث عن الناتج
    generated_files = glob.glob(os.path.join(OUTPUT_DIR, "*.wav"))

    if not generated_files:
        raise RuntimeError("❌ Seed-VC finished but no output file was found")

    latest_file = max(generated_files, key=os.path.getctime)

    return latest_file