# -*- coding: utf-8 -*-
"""seed_vc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19facvZytQpQtwhMvRdVylI3PSVT0nNB4
"""

import os
import uuid
import subprocess
import soundfile as sf


def run_seed(src_audio, tgt_audio, sr=16000):

    src_path = f"/content/{uuid.uuid4()}_src.wav"
    tgt_path = f"/content/{uuid.uuid4()}_tgt.wav"
    out_dir = "/content/seed_out"

    os.makedirs(out_dir, exist_ok=True)

    sf.write(src_path, src_audio, sr)
    sf.write(tgt_path, tgt_audio, sr)

    # 🔥 IMPORTANT: capture errors
    result = subprocess.run(
        [
            "python",
            "seed-vc/inference_v2.py",
            "--source", src_path,
            "--target", tgt_path,
            "--output", out_dir,
            "--diffusion-steps", "50",
            "--similarity-cfg-rate", "0.75",
            "--convert-style", "True"
        ],
        capture_output=True,
        text=True
    )

    print("STDOUT:\n", result.stdout)
    print("STDERR:\n", result.stderr)

    wavs = [f for f in os.listdir(out_dir) if f.endswith(".wav")]

    if len(wavs) == 0:
        raise RuntimeError("❌ Seed-vc failed: no output wav generated")

    return os.path.join(out_dir, sorted(wavs)[-1])