# -*- coding: utf-8 -*-
"""seed_vc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19facvZytQpQtwhMvRdVylI3PSVT0nNB4
"""

import os
import uuid
import subprocess
import soundfile as sf

# تأكد أن هذا المسار هو المجلد الرئيسي للموديل (الذي يحتوي على inference_v2.py)
SEED_DIR = "/content/seed-vc"
OUTPUT_DIR = os.path.join(SEED_DIR, "output_results")

def run_seed(src_audio, tgt_audio, sr=16000):
    # 1. تجهيز الملفات في مجلد /content/ العام لسهولة الوصول
    u_id = str(uuid.uuid4())
    src_path = f"/content/src_{u_id}.wav"
    tgt_path = f"/content/tgt_{u_id}.wav"

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    sf.write(src_path, src_audio, sr)
    sf.write(tgt_path, tgt_audio, sr)

    # 2. بناء الأمر بصيغة String واحدة لتجنب مشاكل argparse
    # سنقوم بدمج أمر الدخول للمجلد (cd) مع أمر التشغيل في سطر واحد
    cmd = (
        f"cd {SEED_DIR} && "
        f"python inference_v2.py "
        f"--source '{src_path}' "
        f"--target '{tgt_path}' "
        f"--output '{OUTPUT_DIR}' "
        f"--diffusion-steps 50 "
        f"--similarity-cfg-rate 0.75 "
        f"--convert-style True"
    )

    print(f"--- Running Seed-VC Engine for ID: {u_id} ---")

    # 3. التنفيذ باستخدام shell=True
    process = subprocess.run(
        cmd,
        shell=True,
        capture_output=True,
        text=True
    )

    # إذا حدث خطأ، سنطبع التفاصيل كاملة
    if process.returncode != 0:
        print("SEED VC ERROR LOG:")
        print(process.stderr)
        raise RuntimeError(f"Seed VC failed. Error: {process.stderr}")

    # 4. البحث عن الملف الناتج (Seed-VC v2 غالباً يضع ID المصدر في اسم الملف)
    wavs = [f for f in os.listdir(OUTPUT_DIR) if f.endswith(".wav")]

    if not wavs:
        raise RuntimeError("Seed VC execution finished but no output file found.")

    # نختار أحدث ملف تم إنشاؤه في مجلد المخرجات
    full_paths = [os.path.join(OUTPUT_DIR, f) for f in wavs]
    latest_file = max(full_paths, key=os.path.getctime)

    return latest_file