# -*- coding: utf-8 -*-
"""spoofing_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AmiPfE8OQl9zW5P575Cqy8_qO1yeokea
"""

import pandas as pd
import os

def build_transcript_inventory(
    source_csv,
    manifest_csv,
    metadata_csv,
    output_csv,
    age_col="mapped_age_class"
):
    """
    Builds transcript inventory:
    segment_id -> sentence
    Saves ONE file per split (adult + minor together)

    Includes:
    - age column (important for cross-age logic)
    - debug flags
    """

    # Load files
    df_source = pd.read_csv(source_csv)
    df_manifest = pd.read_csv(manifest_csv, low_memory=False)
    df_meta = pd.read_csv(metadata_csv)

    # Merge 1: parent_file_id -> path
    df_merged = df_source.merge(
        df_manifest,
        left_on="parent_file_id",
        right_on="file_id",
        how="left"
    )

    # Merge 2: path -> sentence
    df_merged = df_merged.merge(
        df_meta,
        left_on="path",
        right_on="clips_path",
        how="left"
    )

    # Select needed columns
    result = df_merged[
        [
            "segment_id",
            "sentence_id",
            "sentence",
            "clips_path",
            age_col
        ]
    ].copy()   # important to avoid SettingWithCopyWarning

    # Debug flags (KEEP NaN, do not drop)
    result.loc[:, "has_transcript"] = result["sentence"].notna()
    result.loc[:, "is_matched"] = result["clips_path"].notna()

    # Create folder if needed
    os.makedirs(os.path.dirname(output_csv), exist_ok=True)

    # Save
    result.to_csv(output_csv, index=False)

    print(f"\n✅ Saved transcript file:")
    print(output_csv)
    print(f"Total rows: {len(result)}")
    print(f"With transcript: {result['has_transcript'].sum()}")
    print(f"Without transcript: {(~result['has_transcript']).sum()}")

    return result