# -*- coding: utf-8 -*-
"""spoofing_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AmiPfE8OQl9zW5P575Cqy8_qO1yeokea
"""

import pandas as pd
import os

def build_transcript_inventory(
    source_csv,
    manifest_csv,
    metadata_csv,
    output_csv,
    age_col="mapped_age_class"
):

    # ===== Load files =====
    df_source = pd.read_csv(source_csv)
    df_manifest = pd.read_csv(manifest_csv, low_memory=False)
    df_meta = pd.read_csv(metadata_csv)

    # ===== 1. FILTER common_voice ONLY =====
    df_source = df_source[df_source["dataset_source"] == "common_voice"].copy()
    print(f"After filtering common_voice: {len(df_source)} rows")

    # ===== 2. Merge: source -> manifest =====
    df_merged = df_source.merge(
        df_manifest,
        left_on="parent_file_id",
        right_on="file_id",
        how="left"
    )

    # ===== 3. Merge: manifest -> metadata =====
    df_merged = df_merged.merge(
        df_meta,
        left_on="path",
        right_on="clips_path",
        how="left"
    )

    # ===== 4. Select required columns (KEEP ALL ROWS) =====
    result = df_merged[
        [
            "segment_id",
            "sentence_id",
            "sentence",
            "clips_path",
            age_col
        ]
    ].copy()

    # ===== 5. Debug flags =====
    result["has_transcript"] = result["sentence"].notna()

    # ===== 6. Save =====
    os.makedirs(os.path.dirname(output_csv), exist_ok=True)
    result.to_csv(output_csv, index=False)

    print("\n✅ Saved transcript file:")
    print(output_csv)
    print(f"Total rows: {len(result)}")
    print(f"With transcript: {result['has_transcript'].sum()}")
    print(f"Without transcript: {(~result['has_transcript']).sum()}")

    return result