# -*- coding: utf-8 -*-
"""
TTS Engine Dispatcher

This module acts as a unified interface for multiple Text-to-Speech (TTS)
systems.

It:
- Provides a single entry point for different TTS models.
- Routes the input text and reference audio to the selected engine.
- Supports multiple backend implementations (Koko, Chatterbox, XTTSv2).
- Returns a NumPy waveform regardless of the underlying model.

This abstraction makes it easy to switch between TTS models without
changing the rest of the pipeline.
"""

import numpy as np

# Import individual TTS engines
from koko_tts import run_koko_tts
from chatterbox_tts import run_chatterbox_tts
from XTTSv2_tts import run_XTTSv2_tts


# ─────────────────────────────────────────
# ENGINE REGISTRY
# ─────────────────────────────────────────

# Dictionary mapping model names to their corresponding functions
# Each function must return a NumPy audio waveform
TTS_ENGINES = {
    "koko": run_koko_tts,
    "chatterbox": run_chatterbox_tts,
    "xttsv2": run_XTTSv2_tts
}


# ─────────────────────────────────────────
# MAIN DISPATCH FUNCTION
# ─────────────────────────────────────────
def run_tts_on_file(
    text: str,
    reference_audio_path: str,
    model_name: str,
) -> np.ndarray:
    """
    Run TTS using the selected engine.

    Args:
        text                 : input text to synthesize
        reference_audio_path : speaker reference audio
        model_name           : which TTS model to use (koko, chatterbox, xttsv2)

    Returns:
        np.ndarray waveform generated by selected model
    """

    # Select correct engine based on model name
    engine_fn = TTS_ENGINES[model_name]

    # Call the selected TTS engine
    return engine_fn(
        text=text,
        reference_audio_path=reference_audio_path,
    )
