# -*- coding: utf-8 -*-
"""Untitled33.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F74s-JEJIIOwsu-radQSesx-FD-AZnq_
"""

# ============================================
# kNN-VC Voice Cloning - Structured Version
# ============================================
import os
import torch
import librosa
import soundfile as sf
import numpy as np
import sys
import IPython.display as ipd
from google.colab import files

# ============================================
# Setup & Model Loading
# ============================================
def setup_knnvc():
    """Clone repo and load kNN-VC model"""
    if not os.path.exists('/content/knn-vc'):
        os.system('git clone https://github.com/bshall/knn-vc.git')

    if '/content/knn-vc' not in sys.path:
        sys.path.insert(0, '/content/knn-vc')

    from hubconf import knn_vc
    device = 'cuda' if torch.cuda.is_available() else 'cpu'

    model = knn_vc(
        pretrained=True,
        progress=True,
        prematched=True,
        device=device
    )
    print(f" Model loaded on {device}")
    return model

# ============================================
# Core Processing Function
# ============================================
def process_voice_cloning(model, source_path, reference_path, topk=4):
    """
    Convert source voice to match reference voice timbre.

    Args:
        model       : kNN-VC model instance
        source_path : path to source audio (child voice)
        reference_path: path to reference audio (target speaker)
        topk        : number of nearest neighbors (default=4)

    Returns:
        out_wav (np.ndarray): converted audio at 16kHz
    """
    # Resample both inputs to 16kHz
    y_source, _ = librosa.load(source_path, sr=16000)
    y_ref, _    = librosa.load(reference_path, sr=16000)

    src_16k = '/content/_src_16k.wav'
    ref_16k = '/content/_ref_16k.wav'
    sf.write(src_16k, y_source, 16000)
    sf.write(ref_16k, y_ref,    16000)

    # Extract features
    query_seq    = model.get_features(src_16k)
    matching_set = model.get_matching_set([ref_16k])

    # kNN matching & synthesis
    out_wav = model.match(query_seq, matching_set, topk=topk)
    return out_wav.cpu().numpy()

# ============================================
# Single File Conversion
# ============================================
def convert_single(model, source_path, reference_path, output_path, topk=4):
    """Convert one file and save result"""
    out = process_voice_cloning(model, source_path, reference_path, topk)
    sf.write(output_path, out, 16000)
    print(f" Saved → {output_path}")
    return output_path

# ============================================
# Dataset Conversion
# ============================================
def convert_dataset(model, input_folder, reference_path, output_folder, topk=4):
    """
    Batch-convert every wav/mp3 in input_folder using one reference voice.

    Args:
        model         : kNN-VC model instance
        input_folder  : folder containing source audio files
        reference_path: single reference speaker audio
        output_folder : where to save converted files
        topk          : number of nearest neighbors
    """
    os.makedirs(output_folder, exist_ok=True)

    for file in os.listdir(input_folder):
        if not file.lower().endswith((".wav", ".mp3")):
            continue

        source_path = os.path.join(input_folder, file)
        name        = os.path.splitext(file)[0]
        out_path    = os.path.join(output_folder, name + "_voice_cloning.wav")

        print(f"🔄 Processing: {file}")
        out = process_voice_cloning(model, source_path, reference_path, topk)
        sf.write(out_path, out, 16000)
        print(f"    Done → {out_path}")

# ============================================
# Interactive Upload (Colab)
# ============================================
def run_interactive(model):
    """Upload files manually and preview results in Colab"""
    print("\n🎤 Upload the source voice:")
    up1 = files.upload()
    source_file = list(up1.keys())[0]
    ipd.display(ipd.Audio(source_file))

    print("\n Upload the reference voice:")
    up2 = files.upload()
    ref_file = list(up2.keys())[0]
    ipd.display(ipd.Audio(ref_file))

    output_path = '/content/output_cloned.wav'
    convert_single(model, source_file, ref_file, output_path)

    print("\n Results:")
    print("  Source voice:")
    ipd.display(ipd.Audio(source_file))
    print("  Reference voice:")
    ipd.display(ipd.Audio(ref_file))
    print("  Converted voice:")
    ipd.display(ipd.Audio(output_path))

# ============================================
# Main
# ============================================
model = setup_knnvc()

# --- Option A: interactive upload (single file) ---
run_interactive(model)

# --- Option B: batch dataset conversion ---
# convert_dataset(
#     model,
#     input_folder   = '/content/my_dataset',
#     reference_path = '/content/reference_man.wav',
#     output_folder  = '/content/output_dataset'
# )