# -*- coding: utf-8 -*-
"""Voice_Conversion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H-hzlCa_5zU7MnEK0BYBgkRtlyGvsMdv
"""

import os
import uuid
import librosa
import soundfile as sf
import torch

from hubconf import knn_vc
from core.cloner import KokoClone

OUTPUT_DIR = "vc_outputs"
os.makedirs(OUTPUT_DIR, exist_ok=True)

_koko_model = None

def get_koko():
    global _koko_model
    if _koko_model is None:
        _koko_model = KokoClone()
    return _koko_model


def knn_engine(src_audio, tgt_audio, sr=16000):

    device = "cuda" if torch.cuda.is_available() else "cpu"
    model = knn_vc(pretrained=True, prematched=True, device=device)

    src_path = os.path.join(OUTPUT_DIR, f"{uuid.uuid4()}_src.wav")
    tgt_path = os.path.join(OUTPUT_DIR, f"{uuid.uuid4()}_tgt.wav")
    out_path = os.path.join(OUTPUT_DIR, f"{uuid.uuid4()}_knn.wav")

    sf.write(src_path, src_audio, sr)
    sf.write(tgt_path, tgt_audio, sr)

    query = model.get_features(src_path)
    match = model.get_matching_set([tgt_path])

    out = model.match(query, match, topk=4)

    sf.write(out_path, out.cpu().numpy(), sr)

    return out_path


def koko_engine(src_audio, tgt_audio, sr=16000):

    model = get_koko()

    src_path = os.path.join(OUTPUT_DIR, f"{uuid.uuid4()}_src.wav")
    tgt_path = os.path.join(OUTPUT_DIR, f"{uuid.uuid4()}_tgt.wav")
    out_path = os.path.join(OUTPUT_DIR, f"{uuid.uuid4()}_koko.wav")

    sf.write(src_path, src_audio, sr)
    sf.write(tgt_path, tgt_audio, sr)

    model.convert(
        source_audio=src_path,
        reference_audio=tgt_path,
        output_path=out_path
    )

    return out_path


def seed_engine(src_audio, tgt_audio, sr=16000):

    src_path = os.path.join(OUTPUT_DIR, f"{uuid.uuid4()}_src.wav")
    tgt_path = os.path.join(OUTPUT_DIR, f"{uuid.uuid4()}_tgt.wav")

    sf.write(src_path, src_audio, sr)
    sf.write(tgt_path, tgt_audio, sr)

    os.system(f"""
    python inference_v2.py \
        --source "{src_path}" \
        --target "{tgt_path}" \
        --output "{OUTPUT_DIR}" \
        --diffusion-steps 50 \
        --similarity-cfg-rate 0.75 \
        --convert-style True
    """)

    wavs = [f for f in os.listdir(OUTPUT_DIR) if f.endswith(".wav")]
    latest = os.path.join(OUTPUT_DIR, sorted(wavs)[-1])

    return latest


VC_ENGINES = {
    "knn": knn_engine,
    "koko": koko_engine,
    "seed": seed_engine
}


def run_vc_on_file(source_path, target_path, model_name, sr=16000):

    src_audio, _ = librosa.load(source_path, sr=sr)
    tgt_audio, _ = librosa.load(target_path, sr=sr)

    engine = VC_ENGINES[model_name]

    return engine(src_audio, tgt_audio, sr)