# -*- coding: utf-8 -*-
"""Voice_Conversion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H-hzlCa_5zU7MnEK0BYBgkRtlyGvsMdv
"""

import librosa

from Spoofing.knn_vc import run_knn
from Spoofing.koko_vc import run_koko
from Spoofing.seed_vc import run_seed


VC_ENGINES = {
    "knn": run_knn,
    "koko": run_koko,
    "seed": run_seed
}


def run_vc_on_file(source_path, target_path, model_name, sr=16000):

    src_audio, _ = librosa.load(source_path, sr=sr)
    tgt_audio, _ = librosa.load(target_path, sr=sr)

    return VC_ENGINES[model_name](src_audio, tgt_audio, sr)