# -*- coding: utf-8 -*-
"""Voice_Conversion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H-hzlCa_5zU7MnEK0BYBgkRtlyGvsMdv
"""

# =====================================================
# Voice Conversion Module (ALL-IN-ONE)
# =====================================================
# Contains:
# - knn_vc
# - koko_vc
# - seed_vc
# - run_vc_on_file
# - run_vc_on_folder
# =====================================================

import os
import sys
import torch
import librosa
import soundfile as sf
import subprocess
import random

DEFAULT_SR = 16000

# =====================================================
# PATH SETUP
# =====================================================

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(BASE_DIR, ".."))

KNN_PATH = os.path.join(PROJECT_ROOT, "knn-vc")
KOKO_PATH = os.path.join(PROJECT_ROOT, "kokoclone")
SEED_PATH = os.path.join(PROJECT_ROOT, "seed-vc")

# =====================================================
# LAZY LOAD MODELS
# =====================================================

_knn_model = None
_koko_model = None

def get_knnvc_model():
    global _knn_model

    if _knn_model is None:

        if KNN_PATH not in sys.path:
            sys.path.insert(0, KNN_PATH)

        from hubconf import knn_vc

        device = 'cuda' if torch.cuda.is_available() else 'cpu'

        _knn_model = knn_vc(
            pretrained=True,
            prematched=True,
            device=device
        )

    return _knn_model


def get_koko_model():
    global _koko_model

    if _koko_model is None:

        if KOKO_PATH not in sys.path:
            sys.path.insert(0, KOKO_PATH)

        from core.cloner import KokoClone

        _koko_model = KokoClone()

    return _koko_model

# =====================================================
# VOICE CONVERSION FUNCTIONS
# =====================================================

def knn_vc(source_path, target_path, topk=4, sr=DEFAULT_SR):

    model = get_knnvc_model()

    y_source, _ = librosa.load(source_path, sr=sr)
    y_target, _ = librosa.load(target_path, sr=sr)

    src_file = "temp_src.wav"
    tgt_file = "temp_tgt.wav"

    sf.write(src_file, y_source, sr)
    sf.write(tgt_file, y_target, sr)

    query_seq = model.get_features(src_file)
    matching_set = model.get_matching_set([tgt_file])

    out_wav = model.match(query_seq, matching_set, topk=topk)

    return out_wav.cpu().numpy()


def koko_vc(source_path, target_path, sr=DEFAULT_SR):

    model = get_koko_model()

    output_path = "temp_koko.wav"

    model.convert(
        source_audio=source_path,
        reference_audio=target_path,
        output_path=output_path
    )

    audio, _ = librosa.load(output_path, sr=sr)

    return audio


def seed_vc(source_path, target_path,
            diffusion_steps=50,
            similarity=0.75,
            sr=DEFAULT_SR):

    output_dir = os.path.join(PROJECT_ROOT, "temp_seed")
    os.makedirs(output_dir, exist_ok=True)

    cmd = [
        "python",
        os.path.join(SEED_PATH, "inference_v2.py"),
        "--source", source_path,
        "--target", target_path,
        "--output", output_dir,
        "--diffusion-steps", str(diffusion_steps),
        "--similarity-cfg-rate", str(similarity),
        "--convert-style", "true"
    ]

    subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

    files = [f for f in os.listdir(output_dir) if f.endswith(".wav")]

    if len(files) == 0:
        return None

    output_path = os.path.join(output_dir, files[0])

    audio, _ = librosa.load(output_path, sr=sr)

    return audio

# =====================================================
# REGISTRY
# =====================================================

VC_ENGINES = {
    "knn_vc": knn_vc,
    "koko": koko_vc,
    "seed_vc": seed_vc
}

# =====================================================
# RUN ON FILE
# =====================================================

def run_vc_on_file(source_path, target_path, vc_name):

    engine = VC_ENGINES[vc_name]

    return engine(source_path, target_path)

# =====================================================
# RUN ON FOLDER
# =====================================================

def run_vc_on_folder(source_folder, target_folder, vc_name):

    outputs = []

    source_files = [f for f in os.listdir(source_folder) if f.endswith(".wav")]
    target_files = [f for f in os.listdir(target_folder) if f.endswith(".wav")]

    for s in source_files:

        t = random.choice(target_files)

        if s == t:
            continue

        s_path = os.path.join(source_folder, s)
        t_path = os.path.join(target_folder, t)

        out = run_vc_on_file(s_path, t_path, vc_name)

        outputs.append(out)

    return outputs